import { describe, expect, it } from 'vitest'
import type { CreditCardEntry } from '../types'
import {
  calculateCardCycleAccounting,
  cardEntrySpendingMonth,
  createPaidInvoiceSnapshot,
} from './cardCycleAccounting'

function entry(overrides: Partial<CreditCardEntry>): CreditCardEntry {
  return {
    id: overrides.id ?? 'e1',
    cycle: overrides.cycle ?? 'current',
    description: overrides.description ?? 'Compra',
    purchaseDate: overrides.purchaseDate ?? '10/08',
    cardName: overrides.cardName ?? 'Itaú',
    amount: overrides.amount ?? 100,
    personalAmount: overrides.personalAmount ?? overrides.amount ?? 100,
    remainingAmount: overrides.remainingAmount ?? 0,
    budgetArea: overrides.budgetArea,
    ownerName: overrides.ownerName,
    ownerNote: overrides.ownerNote,
    installmentCurrent: overrides.installmentCurrent,
    installmentTotal: overrides.installmentTotal,
    isRecurring: overrides.isRecurring,
    isPrepaid: overrides.isPrepaid,
    autoGenerated: overrides.autoGenerated,
    sourceEntryId: overrides.sourceEntryId,
  }
}

describe('calculateCardCycleAccounting', () => {
  it('separa a fatura que vence em agosto da fatura que encerra agosto', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-08',
      currentTotal: 1_200,
      currentPersonalTotal: 900,
      nextTotal: 500,
      nextPersonalTotal: 320,
      entries: [
        entry({ id: 'old', cycle: 'current', personalAmount: 900 }),
        entry({
          id: 'closing',
          cycle: 'next',
          personalAmount: 320,
          budgetArea: 'desejos',
        }),
      ],
    })

    expect(result.invoiceThisCycle).toMatchObject({
      dueMonth: '2026-08',
      total: 1_200,
      personalTotal: 900,
      paid: false,
      amountKnown: true,
    })
    expect(result.invoiceFormedByCycle).toMatchObject({
      dueMonth: '2026-09',
      total: 500,
      personalTotal: 320,
      paid: false,
      amountKnown: true,
    })
    expect(result.spendingThisCycle).toMatchObject({
      spendingMonth: '2026-08',
      dueMonth: '2026-09',
      sourceCycle: 'next',
      spentPersonalTotal: 320,
      duePersonalTotal: 320,
      paid: false,
      amountKnown: true,
    })
  })

  it('depois de pagar a fatura anterior mantém setembro como fatura que encerra agosto', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentTotal: 500,
      currentPersonalTotal: 320,
      nextTotal: 250,
      nextPersonalTotal: 150,
      paidInvoices: [
        {
          dueMonth: '2026-08',
          total: 1_200,
          personalTotal: 900,
          paidAt: '2026-08-01T12:00:00.000Z',
          spending: [],
        },
      ],
      entries: [
        entry({
          id: 'aug',
          cycle: 'current',
          personalAmount: 320,
          budgetArea: 'desejos',
        }),
      ],
    })

    expect(result.invoiceThisCycle).toMatchObject({
      dueMonth: '2026-08',
      total: 1_200,
      personalTotal: 900,
      paid: true,
    })
    expect(result.invoiceFormedByCycle).toMatchObject({
      dueMonth: '2026-09',
      total: 500,
      personalTotal: 320,
      paid: false,
    })
    expect(result.spendingThisCycle).toMatchObject({
      sourceCycle: 'current',
      spentPersonalTotal: 320,
      duePersonalTotal: 320,
      paid: false,
    })
  })

  it('mantém antecipado visível no bucket sem somá-lo outra vez à fatura ou às áreas devidas', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentTotal: 0,
      currentPersonalTotal: 0,
      nextTotal: 0,
      nextPersonalTotal: 0,
      entries: [
        entry({
          cycle: 'current',
          personalAmount: 200,
          budgetArea: 'necessidades',
          isPrepaid: true,
        }),
      ],
    })

    expect(result.spendingThisCycle.spentPersonalTotal).toBe(200)
    expect(result.spendingThisCycle.duePersonalTotal).toBe(0)
    expect(result.spendingThisCycle.personalByArea.necessidades).toBe(0)
    expect(result.invoiceFormedByCycle.personalTotal).toBe(0)
  })

  it('usa o bucket da fatura, e não purchaseDate, como fronteira do ciclo', () => {
    const datedInJuly = entry({ cycle: 'current', purchaseDate: '20/07' })
    const datedInAugust = entry({ cycle: 'current', purchaseDate: '01/08' })

    expect(cardEntrySpendingMonth(datedInJuly, '2026-09')).toBe('2026-08')
    expect(cardEntrySpendingMonth(datedInAugust, '2026-09')).toBe('2026-08')
  })

  it('reproduz o fechamento do backup: 4456,02 total e 2511,64 da minha parte', () => {
    const currentEntries = [
      entry({
        id: 'jul-due',
        cycle: 'current',
        purchaseDate: '20/07',
        personalAmount: 843.55,
        budgetArea: 'desejos',
      }),
      entry({
        id: 'jul-prepaid',
        cycle: 'current',
        purchaseDate: '31/07',
        personalAmount: 93.73,
        budgetArea: 'necessidades',
        isPrepaid: true,
      }),
      entry({
        id: 'installments-and-current',
        cycle: 'current',
        purchaseDate: '03/06',
        personalAmount: 1_668.09,
        budgetArea: 'desejos',
        installmentCurrent: 3,
        installmentTotal: 12,
      }),
      entry({
        id: 'aug-prepaid',
        cycle: 'current',
        purchaseDate: '01/08',
        personalAmount: 84.99,
        budgetArea: 'desejos',
        isPrepaid: true,
      }),
    ]

    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentTotal: 4_456.02,
      currentPersonalTotal: 2_511.64,
      nextTotal: 2_698.41,
      nextPersonalTotal: 893.01,
      entries: currentEntries,
    })

    expect(result.invoiceFormedByCycle).toMatchObject({
      dueMonth: '2026-09',
      total: 4_456.02,
      personalTotal: 2_511.64,
      paid: false,
      amountKnown: true,
    })
    expect(result.spendingThisCycle.spentPersonalTotal).toBeCloseTo(2_690.36)
    expect(result.spendingThisCycle.duePersonalTotal).toBeCloseTo(2_511.64)
    expect(result.spendingThisCycle.personalByArea.desejos).toBeCloseTo(2_511.64)
    expect(result.spendingThisCycle.personalByArea.necessidades).toBe(0)
  })

  it('pagar setembro antes de fechar agosto preserva a mesma fatura do ciclo', () => {
    const currentEntries = [
      entry({
        id: 'due-a',
        cycle: 'current',
        purchaseDate: '20/07',
        personalAmount: 843.55,
        budgetArea: 'desejos',
      }),
      entry({
        id: 'prepaid-a',
        cycle: 'current',
        purchaseDate: '31/07',
        personalAmount: 93.73,
        budgetArea: 'necessidades',
        isPrepaid: true,
      }),
      entry({
        id: 'due-b',
        cycle: 'current',
        purchaseDate: '03/06',
        personalAmount: 1_668.09,
        budgetArea: 'desejos',
        installmentCurrent: 3,
        installmentTotal: 12,
      }),
      entry({
        id: 'prepaid-b',
        cycle: 'current',
        purchaseDate: '01/08',
        personalAmount: 84.99,
        budgetArea: 'desejos',
        isPrepaid: true,
      }),
    ]

    const beforePay = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentTotal: 4_456.02,
      currentPersonalTotal: 2_511.64,
      nextTotal: 2_698.41,
      nextPersonalTotal: 893.01,
      entries: currentEntries,
    })
    const snapshot = createPaidInvoiceSnapshot({
      entries: currentEntries,
      currentDueMonth: '2026-09',
      total: 4_456.02,
      personalTotal: 2_511.64,
      paidAt: '2026-08-31T20:00:00.000Z',
    })
    const afterPay = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-10',
      currentTotal: 2_698.41,
      currentPersonalTotal: 893.01,
      nextTotal: 200,
      nextPersonalTotal: 100,
      paidInvoices: [snapshot],
      entries: [],
    })

    expect(beforePay.invoiceFormedByCycle).toMatchObject({
      total: 4_456.02,
      personalTotal: 2_511.64,
      paid: false,
    })
    expect(afterPay.invoiceFormedByCycle).toMatchObject({
      dueMonth: '2026-09',
      total: 4_456.02,
      personalTotal: 2_511.64,
      paid: true,
      amountKnown: true,
    })
    expect(afterPay.spendingThisCycle.duePersonalTotal).toBeCloseTo(
      beforePay.spendingThisCycle.duePersonalTotal,
    )
    expect(afterPay.spendingThisCycle.personalByArea).toEqual(
      beforePay.spendingThisCycle.personalByArea,
    )
  })

  it('snapshot legado preserva a parte pessoal mesmo sem total cheio', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-10',
      currentTotal: 500,
      currentPersonalTotal: 300,
      nextTotal: 250,
      nextPersonalTotal: 150,
      entries: [],
      paidInvoices: [
        {
          dueMonth: '2026-09',
          total: null,
          personalTotal: 400,
          paidAt: '2026-08-31T20:00:00.000Z',
          spending: [],
        },
      ],
    })

    expect(result.invoiceFormedByCycle).toMatchObject({
      dueMonth: '2026-09',
      total: null,
      personalTotal: 400,
      paid: true,
      amountKnown: true,
    })
  })
})
