import { describe, expect, it } from 'vitest'
import type { CreditCardEntry } from '../types'
import {
  calculateCardCycleAccounting,
  createPaidInvoiceSnapshot,
} from './cardCycleAccounting'

function entry(overrides: Partial<CreditCardEntry> & { spendingMonth?: string }): CreditCardEntry {
  return {
    id: overrides.id ?? 'e1',
    cycle: overrides.cycle ?? 'current',
    description: overrides.description ?? 'Compra',
    purchaseDate: overrides.purchaseDate ?? '10/08',
    cardName: overrides.cardName ?? 'Itaú',
    amount: overrides.amount ?? 100,
    personalAmount: overrides.personalAmount ?? overrides.amount ?? 100,
    remainingAmount: overrides.remainingAmount ?? 0,
    budgetArea: overrides.budgetArea,
    ownerName: overrides.ownerName,
    ownerNote: overrides.ownerNote,
    installmentCurrent: overrides.installmentCurrent,
    installmentTotal: overrides.installmentTotal,
    isRecurring: overrides.isRecurring,
    isPrepaid: overrides.isPrepaid,
    autoGenerated: overrides.autoGenerated,
    sourceEntryId: overrides.sourceEntryId,
    spendingMonth: overrides.spendingMonth,
  } as CreditCardEntry
}

describe('calculateCardCycleAccounting', () => {
  it('antes de pagar a fatura anterior separa caixa de agosto das compras de agosto', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-08',
      currentPersonalTotal: 900,
      entries: [
        entry({ id: 'jul', cycle: 'current', spendingMonth: '2026-07', personalAmount: 900 }),
        entry({
          id: 'ago',
          cycle: 'next',
          spendingMonth: '2026-08',
          personalAmount: 320,
          budgetArea: 'desejos',
        }),
      ],
    })

    expect(result.invoiceThisCycle).toMatchObject({
      dueMonth: '2026-08',
      personalTotal: 900,
      paid: false,
      amountKnown: true,
    })
    expect(result.spendingThisCycle).toMatchObject({
      spendingMonth: '2026-08',
      dueMonth: '2026-09',
      sourceCycle: 'next',
      spentPersonalTotal: 320,
      duePersonalTotal: 320,
      paid: false,
      amountKnown: true,
    })
  })

  it('depois de pagar a fatura anterior lê agosto na fatura corrente de setembro', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentPersonalTotal: 320,
      paidInvoices: [
        {
          dueMonth: '2026-08',
          personalTotal: 900,
          paidAt: '2026-08-01T12:00:00.000Z',
          spending: [],
        },
      ],
      entries: [
        entry({
          id: 'ago',
          cycle: 'current',
          spendingMonth: '2026-08',
          personalAmount: 320,
          budgetArea: 'desejos',
        }),
      ],
    })

    expect(result.invoiceThisCycle).toMatchObject({ personalTotal: 900, paid: true })
    expect(result.spendingThisCycle).toMatchObject({
      sourceCycle: 'current',
      spentPersonalTotal: 320,
      duePersonalTotal: 320,
      paid: false,
    })
  })

  it('antecipado consome o orçamento do mês mas não fica devido na fatura', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentPersonalTotal: 0,
      entries: [
        entry({
          cycle: 'current',
          spendingMonth: '2026-08',
          personalAmount: 200,
          budgetArea: 'necessidades',
          isPrepaid: true,
        }),
      ],
    })

    expect(result.spendingThisCycle.spentPersonalTotal).toBe(200)
    expect(result.spendingThisCycle.duePersonalTotal).toBe(0)
    expect(result.spendingThisCycle.personalByArea.necessidades).toBe(200)
  })

  it('pagar a fatura de setembro antes de fechar agosto preserva exatamente o mesmo realizado', () => {
    const augustEntries = [
      entry({
        id: 'due',
        cycle: 'current',
        spendingMonth: '2026-08',
        personalAmount: 2_511.64,
        budgetArea: 'desejos',
      }),
      entry({
        id: 'prepaid',
        cycle: 'current',
        spendingMonth: '2026-08',
        personalAmount: 178.72,
        budgetArea: 'necessidades',
        isPrepaid: true,
      }),
    ]

    const beforePay = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-09',
      currentPersonalTotal: 2_511.64,
      entries: augustEntries,
    })
    const snapshot = createPaidInvoiceSnapshot({
      entries: augustEntries,
      currentDueMonth: '2026-09',
      personalTotal: 2_511.64,
      paidAt: '2026-08-31T20:00:00.000Z',
    })
    const afterPay = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-10',
      currentPersonalTotal: 0,
      paidInvoices: [snapshot],
      entries: [],
    })

    expect(beforePay.spendingThisCycle.spentPersonalTotal).toBeCloseTo(2_690.36)
    expect(beforePay.spendingThisCycle.duePersonalTotal).toBeCloseTo(2_511.64)
    expect(afterPay.spendingThisCycle).toMatchObject({
      spendingMonth: '2026-08',
      dueMonth: '2026-09',
      paid: true,
      amountKnown: true,
    })
    expect(afterPay.spendingThisCycle.spentPersonalTotal).toBeCloseTo(
      beforePay.spendingThisCycle.spentPersonalTotal,
    )
    expect(afterPay.spendingThisCycle.duePersonalTotal).toBeCloseTo(
      beforePay.spendingThisCycle.duePersonalTotal,
    )
    expect(afterPay.spendingThisCycle.personalByArea).toEqual(
      beforePay.spendingThisCycle.personalByArea,
    )
  })

  it('sinaliza detalhe desconhecido quando uma versão antiga já girou sem snapshot de competência', () => {
    const result = calculateCardCycleAccounting({
      activeCycleMonth: '2026-08',
      currentDueMonth: '2026-10',
      currentPersonalTotal: 500,
      entries: [entry({ cycle: 'current', spendingMonth: '2026-09', personalAmount: 500 })],
      paidInvoices: [
        {
          dueMonth: '2026-09',
          personalTotal: 400,
          paidAt: '2026-08-31T20:00:00.000Z',
          spending: [],
        },
      ],
    })

    expect(result.spendingThisCycle).toMatchObject({
      spentPersonalTotal: 0,
      duePersonalTotal: 0,
      paid: false,
      amountKnown: false,
    })
  })
})
