import type {
  BudgetArea,
  CreditCardEntry,
  CreditCardSettings,
  CreditCardSummary,
} from '../types'
import { BUDGET_AREAS } from '../types/constants'
import { finiteNumber, normalizeText, uid } from './shared'

const isBudgetArea = (value: unknown): value is BudgetArea =>
  typeof value === 'string' && (BUDGET_AREAS as string[]).includes(value)

export function normalizeCreditCardEntry(entry: CreditCardEntry): CreditCardEntry {
  const amount = finiteNumber(entry.amount)
  const installmentCurrent = finiteNumber(entry.installmentCurrent)
  const installmentTotal = finiteNumber(entry.installmentTotal)

  return {
    id: entry.id || uid(),
    cycle: entry.cycle === 'next' ? 'next' : 'current',
    description: entry.description?.trim() || 'Lançamento sem descrição',
    purchaseDate: entry.purchaseDate?.trim() || '',
    cardName: entry.cardName?.trim() || 'Cartão',
    amount,
    personalAmount: finiteNumber(entry.personalAmount, amount),
    remainingAmount: finiteNumber(entry.remainingAmount),
    budgetArea: isBudgetArea(entry.budgetArea) ? entry.budgetArea : undefined,
    ownerName: entry.ownerName?.trim() || '',
    ownerNote: entry.ownerNote?.trim() || '',
    installmentCurrent: installmentCurrent > 0 ? installmentCurrent : undefined,
    installmentTotal: installmentTotal > 0 ? installmentTotal : undefined,
    isRecurring: entry.isRecurring === true ? true : undefined,
    isPrepaid: entry.isPrepaid === true ? true : undefined,
    autoGenerated: entry.autoGenerated === true ? true : undefined,
    sourceEntryId: entry.sourceEntryId || undefined,
  }
}

export function buildRemainingInstallmentsAmount(amount: number, current?: number, total?: number) {
  if (!current || !total || current >= total) return 0
  return amount * (total - current)
}

function creditCardPurchaseKey(entry: CreditCardEntry) {
  return `${normalizeText(entry.description)}|${normalizeText(entry.cardName)}`
}

/**
 * Recalcula os lançamentos gerados automaticamente da próxima fatura a partir da
 * fatura atual: assinaturas recorrentes repetem e compras parceladas seguem para
 * a parcela seguinte. Lançamentos manuais da próxima fatura são mantidos e
 * bloqueiam a geração de duplicatas da mesma compra.
 */
export function syncGeneratedNextEntries(entries: CreditCardEntry[]): CreditCardEntry[] {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const manualNextEntries = entries.filter(
    (entry) => entry.cycle === 'next' && !entry.autoGenerated,
  )
  const manualNextKeys = new Set(manualNextEntries.map(creditCardPurchaseKey))
  const manualNextSourceIds = new Set(
    manualNextEntries.map((entry) => entry.sourceEntryId).filter(Boolean),
  )
  const isCoveredByManualEntry = (entry: CreditCardEntry) =>
    manualNextKeys.has(creditCardPurchaseKey(entry)) || manualNextSourceIds.has(entry.id)
  const generated: CreditCardEntry[] = []

  for (const entry of currentEntries) {
    if (!entry.isRecurring || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        remainingAmount: 0,
        // Antecipar o pagamento vale só para o ciclo atual; a próxima cobrança volta a ser devida.
        isPrepaid: undefined,
      }),
    )
  }

  const latestInstallments = new Map<string, CreditCardEntry>()
  for (const entry of currentEntries) {
    if (entry.isRecurring || !entry.installmentCurrent || !entry.installmentTotal) continue
    const key = `${creditCardPurchaseKey(entry)}|${entry.installmentTotal}`
    const existing = latestInstallments.get(key)
    if (!existing || entry.installmentCurrent > (existing.installmentCurrent ?? 0)) {
      latestInstallments.set(key, entry)
    }
  }

  for (const entry of latestInstallments.values()) {
    const nextInstallment = (entry.installmentCurrent ?? 0) + 1
    const total = entry.installmentTotal ?? 0
    if (nextInstallment > total || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        installmentCurrent: nextInstallment,
        remainingAmount: buildRemainingInstallmentsAmount(entry.amount, nextInstallment, total),
        isPrepaid: undefined,
      }),
    )
  }

  return [...currentEntries, ...manualNextEntries, ...generated]
}

export function calculateCreditCardSummary(
  entries: CreditCardEntry[],
  settings: CreditCardSettings,
): CreditCardSummary {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const nextEntries = entries.filter((entry) => entry.cycle === 'next')
  // Compras pagas antecipadamente continuam listadas, mas não são mais devidas:
  // ficam fora dos totais da fatura, do limite pessoal e dos agrupamentos.
  const currentDueEntries = currentEntries.filter((entry) => !entry.isPrepaid)
  const currentPrepaidEntries = currentEntries.filter((entry) => entry.isPrepaid)
  const currentTotal = currentDueEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalTotal = currentDueEntries.reduce(
    (sum, entry) => sum + entry.personalAmount,
    0,
  )
  const currentThirdPartyTotal = currentDueEntries.reduce(
    (sum, entry) => sum + Math.max(0, entry.amount - entry.personalAmount),
    0,
  )
  const currentPrepaidTotal = currentPrepaidEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalPrepaidTotal = currentPrepaidEntries.reduce(
    (sum, entry) => sum + entry.personalAmount,
    0,
  )
  const nextTotal = nextEntries.reduce(
    (sum, entry) => sum + (entry.isPrepaid ? 0 : entry.amount),
    0,
  )
  const nextPersonalTotal = nextEntries.reduce(
    (sum, entry) => sum + (entry.isPrepaid ? 0 : entry.personalAmount),
    0,
  )
  const remainingInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + entry.remainingAmount,
    0,
  )
  const remainingPersonalInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + (entry.personalAmount / (entry.amount || 1)) * entry.remainingAmount,
    0,
  )

  const byCard = new Map<string, { totalAmount: number; personalAmount: number }>()
  const byOwner = new Map<string, { totalAmount: number; personalAmount: number }>()
  // Uma compra antecipada já saiu do bolso neste mês: continua contando como
  // gasto realizado da área, mesmo fora do total devido da fatura.
  const personalByArea: Record<BudgetArea, number> = {
    necessidades: 0,
    desejos: 0,
    investimentos: 0,
  }
  let unclassifiedPersonal = 0

  for (const entry of currentEntries) {
    if (entry.budgetArea) personalByArea[entry.budgetArea] += entry.personalAmount
    else unclassifiedPersonal += entry.personalAmount
  }

  for (const entry of currentDueEntries) {
    const existing = byCard.get(entry.cardName) ?? { totalAmount: 0, personalAmount: 0 }
    byCard.set(entry.cardName, {
      totalAmount: existing.totalAmount + entry.amount,
      personalAmount: existing.personalAmount + entry.personalAmount,
    })

    const thirdPartyAmount = Math.max(0, entry.amount - entry.personalAmount)
    if (thirdPartyAmount > 0) {
      const owner = entry.ownerName || entry.ownerNote || 'Outro'
      const ownerExisting = byOwner.get(owner) ?? { totalAmount: 0, personalAmount: 0 }
      byOwner.set(owner, {
        totalAmount: ownerExisting.totalAmount + thirdPartyAmount,
        personalAmount: ownerExisting.personalAmount,
      })
    }
  }

  return {
    currentTotal,
    currentPersonalTotal,
    currentThirdPartyTotal,
    currentPrepaidTotal,
    currentPersonalPrepaidTotal,
    nextTotal,
    nextPersonalTotal,
    remainingInstallmentsTotal,
    remainingPersonalInstallmentsTotal,
    availablePersonalLimit: settings.personalSpendingLimit - currentPersonalTotal,
    totalsByCard: Array.from(byCard.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    totalsByOwner: Array.from(byOwner.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    currentEntriesCount: currentEntries.length,
    nextEntriesCount: nextEntries.length,
    personalByArea,
    unclassifiedPersonal,
  }
}
