import type {
  BudgetArea,
  CardCycleStatus,
  CreditCardAccount,
  CreditCardEntry,
  CreditCardSettings,
  CreditCardSummary,
} from '../types'
import { BUDGET_AREAS } from '../types/constants'
import { finiteNumber, normalizeText, uid } from './shared'

const DAY_MS = 24 * 60 * 60 * 1000

export function normalizeCardAccount(raw: Partial<CreditCardAccount> | undefined): CreditCardAccount {
  const clampDay = (value: unknown, fallback: number) =>
    Math.max(1, Math.min(31, Math.round(finiteNumber(value, fallback))))

  return {
    id: raw?.id || uid(),
    name: raw?.name?.trim() || 'Cartão',
    closingDay: clampDay(raw?.closingDay, 30),
    dueDay: clampDay(raw?.dueDay, 5),
    limit: Math.max(0, finiteNumber(raw?.limit)),
  }
}

/** Extrai o dia de um texto livre de vencimento antigo ("05/07" → 5). */
export function parsePaymentDay(raw: string | undefined, fallback = 5): number {
  const match = raw?.match(/(\d{1,2})/)
  const day = match ? Number(match[1]) : NaN
  return Number.isFinite(day) && day >= 1 && day <= 31 ? day : fallback
}

/** Próxima ocorrência de um dia do mês, a partir de `from`. */
function nextDateForDay(day: number, from: Date): Date {
  const daysInMonth = new Date(from.getFullYear(), from.getMonth() + 1, 0).getDate()
  const thisMonth = new Date(from.getFullYear(), from.getMonth(), Math.min(day, daysInMonth))
  if (thisMonth.getTime() >= startOfDay(from).getTime()) return thisMonth
  const nextDaysInMonth = new Date(from.getFullYear(), from.getMonth() + 2, 0).getDate()
  return new Date(from.getFullYear(), from.getMonth() + 1, Math.min(day, nextDaysInMonth))
}

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate())
}

/**
 * Onde cada cartão está no seu ciclo. Com fechamentos diferentes, "a fatura" não
 * é uma coisa só: um cartão pode ter fechado ontem e o outro fechar só semana
 * que vem — e o que já fechou não aceita mais compras deste ciclo.
 */
export function describeCardCycles(
  accounts: CreditCardAccount[],
  summary: CreditCardSummary,
  now = new Date(),
): CardCycleStatus[] {
  const today = startOfDay(now)
  const days = (target: Date) => Math.round((target.getTime() - today.getTime()) / DAY_MS)

  return accounts.map((account) => {
    const totals = summary.totalsByCard.find(
      (card) => normalizeText(card.cardName) === normalizeText(account.name),
    )
    const personalAmount = totals?.personalAmount ?? 0
    const totalAmount = totals?.totalAmount ?? 0
    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()
    const closingThisMonth = Math.min(account.closingDay, daysInMonth)

    return {
      ...account,
      isClosed: now.getDate() > closingThisMonth,
      daysToClosing: days(nextDateForDay(account.closingDay, now)),
      daysToDue: days(nextDateForDay(account.dueDay, now)),
      personalAmount,
      totalAmount,
      usagePct: account.limit > 0 ? (totalAmount / account.limit) * 100 : null,
    }
  })
}

/** Nomes de cartão que aparecem nos lançamentos mas não estão cadastrados. */
export function unregisteredCardNames(
  entries: CreditCardEntry[],
  accounts: CreditCardAccount[],
): string[] {
  const known = new Set(accounts.map((account) => normalizeText(account.name)))
  const names = new Map<string, string>()
  for (const entry of entries) {
    const key = normalizeText(entry.cardName)
    if (!key || known.has(key) || names.has(key)) continue
    names.set(key, entry.cardName)
  }
  return Array.from(names.values())
}

const isBudgetArea = (value: unknown): value is BudgetArea =>
  typeof value === 'string' && (BUDGET_AREAS as string[]).includes(value)

export function normalizeCreditCardEntry(entry: CreditCardEntry): CreditCardEntry {
  const amount = finiteNumber(entry.amount)
  const installmentCurrent = finiteNumber(entry.installmentCurrent)
  const installmentTotal = finiteNumber(entry.installmentTotal)

  return {
    id: entry.id || uid(),
    cycle: entry.cycle === 'next' ? 'next' : 'current',
    description: entry.description?.trim() || 'Lançamento sem descrição',
    purchaseDate: entry.purchaseDate?.trim() || '',
    cardName: entry.cardName?.trim() || 'Cartão',
    amount,
    personalAmount: finiteNumber(entry.personalAmount, amount),
    remainingAmount: finiteNumber(entry.remainingAmount),
    budgetArea: isBudgetArea(entry.budgetArea) ? entry.budgetArea : undefined,
    ownerName: entry.ownerName?.trim() || '',
    ownerNote: entry.ownerNote?.trim() || '',
    installmentCurrent: installmentCurrent > 0 ? installmentCurrent : undefined,
    installmentTotal: installmentTotal > 0 ? installmentTotal : undefined,
    isRecurring: entry.isRecurring === true ? true : undefined,
    isPrepaid: entry.isPrepaid === true ? true : undefined,
    autoGenerated: entry.autoGenerated === true ? true : undefined,
    sourceEntryId: entry.sourceEntryId || undefined,
  }
}

export function buildRemainingInstallmentsAmount(amount: number, current?: number, total?: number) {
  if (!current || !total || current >= total) return 0
  return amount * (total - current)
}

function creditCardPurchaseKey(entry: CreditCardEntry) {
  return `${normalizeText(entry.description)}|${normalizeText(entry.cardName)}`
}

/**
 * Recalcula os lançamentos gerados automaticamente da próxima fatura a partir da
 * fatura atual: assinaturas recorrentes repetem e compras parceladas seguem para
 * a parcela seguinte. Lançamentos manuais da próxima fatura são mantidos e
 * bloqueiam a geração de duplicatas da mesma compra.
 */
export function syncGeneratedNextEntries(entries: CreditCardEntry[]): CreditCardEntry[] {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const manualNextEntries = entries.filter(
    (entry) => entry.cycle === 'next' && !entry.autoGenerated,
  )
  const manualNextKeys = new Set(manualNextEntries.map(creditCardPurchaseKey))
  const manualNextSourceIds = new Set(
    manualNextEntries.map((entry) => entry.sourceEntryId).filter(Boolean),
  )
  const isCoveredByManualEntry = (entry: CreditCardEntry) =>
    manualNextKeys.has(creditCardPurchaseKey(entry)) || manualNextSourceIds.has(entry.id)
  const generated: CreditCardEntry[] = []

  for (const entry of currentEntries) {
    if (!entry.isRecurring || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        remainingAmount: 0,
        // Antecipar o pagamento vale só para o ciclo atual; a próxima cobrança volta a ser devida.
        isPrepaid: undefined,
      }),
    )
  }

  const latestInstallments = new Map<string, CreditCardEntry>()
  for (const entry of currentEntries) {
    if (entry.isRecurring || !entry.installmentCurrent || !entry.installmentTotal) continue
    const key = `${creditCardPurchaseKey(entry)}|${entry.installmentTotal}`
    const existing = latestInstallments.get(key)
    if (!existing || entry.installmentCurrent > (existing.installmentCurrent ?? 0)) {
      latestInstallments.set(key, entry)
    }
  }

  for (const entry of latestInstallments.values()) {
    const nextInstallment = (entry.installmentCurrent ?? 0) + 1
    const total = entry.installmentTotal ?? 0
    if (nextInstallment > total || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        installmentCurrent: nextInstallment,
        remainingAmount: buildRemainingInstallmentsAmount(entry.amount, nextInstallment, total),
        isPrepaid: undefined,
      }),
    )
  }

  return [...currentEntries, ...manualNextEntries, ...generated]
}

export function calculateCreditCardSummary(
  entries: CreditCardEntry[],
  settings: CreditCardSettings,
): CreditCardSummary {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const nextEntries = entries.filter((entry) => entry.cycle === 'next')
  // Compras pagas antecipadamente continuam listadas, mas não são mais devidas:
  // ficam fora dos totais da fatura, do limite pessoal e dos agrupamentos.
  const currentDueEntries = currentEntries.filter((entry) => !entry.isPrepaid)
  const currentPrepaidEntries = currentEntries.filter((entry) => entry.isPrepaid)
  const currentTotal = currentDueEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalTotal = currentDueEntries.reduce(
    (sum, entry) => sum + entry.personalAmount,
    0,
  )
  const currentThirdPartyTotal = currentDueEntries.reduce(
    (sum, entry) => sum + Math.max(0, entry.amount - entry.personalAmount),
    0,
  )
  const currentPrepaidTotal = currentPrepaidEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalPrepaidTotal = currentPrepaidEntries.reduce(
    (sum, entry) => sum + entry.personalAmount,
    0,
  )
  const nextTotal = nextEntries.reduce(
    (sum, entry) => sum + (entry.isPrepaid ? 0 : entry.amount),
    0,
  )
  const nextPersonalTotal = nextEntries.reduce(
    (sum, entry) => sum + (entry.isPrepaid ? 0 : entry.personalAmount),
    0,
  )
  const remainingInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + entry.remainingAmount,
    0,
  )
  const remainingPersonalInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + (entry.personalAmount / (entry.amount || 1)) * entry.remainingAmount,
    0,
  )

  const byCard = new Map<
    string,
    { totalAmount: number; personalAmount: number; thirdPartyAmount: number }
  >()
  const byOwner = new Map<
    string,
    { totalAmount: number; personalAmount: number; thirdPartyAmount: number }
  >()
  // Uma compra antecipada já saiu do bolso neste mês: continua contando como
  // gasto realizado da área, mesmo fora do total devido da fatura.
  const personalByArea: Record<BudgetArea, number> = {
    necessidades: 0,
    desejos: 0,
    investimentos: 0,
  }
  let unclassifiedPersonal = 0

  for (const entry of currentEntries) {
    if (entry.budgetArea) personalByArea[entry.budgetArea] += entry.personalAmount
    else unclassifiedPersonal += entry.personalAmount
  }

  for (const entry of currentDueEntries) {
    const thirdPartyAmount = Math.max(0, entry.amount - entry.personalAmount)
    const existing = byCard.get(entry.cardName) ?? {
      totalAmount: 0,
      personalAmount: 0,
      thirdPartyAmount: 0,
    }
    byCard.set(entry.cardName, {
      totalAmount: existing.totalAmount + entry.amount,
      personalAmount: existing.personalAmount + entry.personalAmount,
      thirdPartyAmount: existing.thirdPartyAmount + thirdPartyAmount,
    })

    if (thirdPartyAmount > 0) {
      const owner = entry.ownerName || entry.ownerNote || 'Outro'
      const ownerExisting = byOwner.get(owner) ?? {
        totalAmount: 0,
        personalAmount: 0,
        thirdPartyAmount: 0,
      }
      byOwner.set(owner, {
        totalAmount: ownerExisting.totalAmount + thirdPartyAmount,
        personalAmount: ownerExisting.personalAmount,
        thirdPartyAmount: ownerExisting.thirdPartyAmount + thirdPartyAmount,
      })
    }
  }

  return {
    currentTotal,
    currentPersonalTotal,
    currentThirdPartyTotal,
    currentPrepaidTotal,
    currentPersonalPrepaidTotal,
    nextTotal,
    nextPersonalTotal,
    remainingInstallmentsTotal,
    remainingPersonalInstallmentsTotal,
    availablePersonalLimit: settings.personalSpendingLimit - currentPersonalTotal,
    totalsByCard: Array.from(byCard.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    totalsByOwner: Array.from(byOwner.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    currentEntriesCount: currentEntries.length,
    nextEntriesCount: nextEntries.length,
    personalByArea,
    unclassifiedPersonal,
  }
}
