import { useCallback, useEffect, useMemo, useRef } from 'react'
import { useLocalStorage } from './useLocalStorage'
import type {
  CreditCardAccount,
  CreditCardCycle,
  CreditCardEntry,
  CreditCardSettings,
} from '../types'
import {
  advanceCreditCardSettingsCycle,
  buildRemainingInstallmentsAmount,
  calculateCreditCardSummary,
  describeCardCycles,
  normalizeCreditCardSettings,
  normalizeCardAccount,
  normalizeCreditCardEntry,
  parsePaymentDay,
  syncGeneratedNextEntries,
  unregisteredCardNames,
} from '../lib/creditCards'
import { readJson, uid } from '../lib/shared'

const ENTRIES_STORAGE_KEY = 'uf_credit_card_entries_v1'
const SETTINGS_STORAGE_KEY = 'uf_credit_card_settings_v1'
const ACCOUNTS_STORAGE_KEY = 'uf_credit_card_accounts_v1'
const DEFAULT_SETTINGS: CreditCardSettings = { paymentDate: '05/07', personalSpendingLimit: 1500 }

/**
 * Cada cartão passou a ter fechamento e vencimento próprios. Na primeira carga,
 * os cartões que já apareciam nos lançamentos são cadastrados herdando o
 * vencimento global antigo — nada se perde e nada precisa ser redigitado.
 */
function loadInitialAccounts(): CreditCardAccount[] {
  const stored = readJson<CreditCardAccount[] | null>(ACCOUNTS_STORAGE_KEY, null)
  if (Array.isArray(stored) && stored.length) return stored.map(normalizeCardAccount)

  const entries = readJson<CreditCardEntry[] | null>(ENTRIES_STORAGE_KEY, null)
  if (!Array.isArray(entries) || entries.length === 0) return []

  const settings = readJson<Partial<CreditCardSettings> | null>(SETTINGS_STORAGE_KEY, null)
  const dueDay = parsePaymentDay(settings?.paymentDate, 5)
  const names = Array.from(
    new Set(entries.map((entry) => entry?.cardName?.trim()).filter((name): name is string => !!name)),
  )

  return names.map((name) => normalizeCardAccount({ name, closingDay: 30, dueDay }))
}

export function useCreditCards() {
  const [storedEntries, setEntries] = useLocalStorage<CreditCardEntry[]>(ENTRIES_STORAGE_KEY, [])
  const entries = useMemo(
    () => (Array.isArray(storedEntries) ? storedEntries.map(normalizeCreditCardEntry) : []),
    [storedEntries],
  )
  const [storedSettings, setSettingsRaw] = useLocalStorage<CreditCardSettings>(
    SETTINGS_STORAGE_KEY,
    DEFAULT_SETTINGS,
  )
  const settings = useMemo(() => normalizeCreditCardSettings(storedSettings), [storedSettings])
  const [storedAccounts, setStoredAccounts] = useLocalStorage<CreditCardAccount[]>(
    ACCOUNTS_STORAGE_KEY,
    loadInitialAccounts,
  )
  const accounts = useMemo(
    () => (Array.isArray(storedAccounts) ? storedAccounts.map(normalizeCardAccount) : []),
    [storedAccounts],
  )

  // Os cartões herdados dos lançamentos só existem em memória até a primeira
  // gravação; persiste-os no mount para a migração não se perder.
  useEffect(() => {
    if (window.localStorage.getItem(ACCOUNTS_STORAGE_KEY) === null && accounts.length > 0) {
      setStoredAccounts(accounts)
    }
  }, [accounts, setStoredAccounts])

  // A geração da próxima fatura roda a cada mutação, mas dados que chegam
  // prontos (backup importado, outro dispositivo) nunca passaram por uma:
  // sem isto, assinaturas e parcelas só apareceriam na próxima edição.
  const syncedOnMount = useRef(false)
  useEffect(() => {
    if (syncedOnMount.current || entries.length === 0) return
    syncedOnMount.current = true
    setEntries((prev) => {
      const synced = syncGeneratedNextEntries(prev.map(normalizeCreditCardEntry))
      return synced.length === prev.length ? prev : synced
    })
  }, [entries.length, setEntries])

  const addEntry = useCallback(
    (entry: Omit<CreditCardEntry, 'id'>) => {
      setEntries((prev) => {
        const nextEntries = [...prev, normalizeCreditCardEntry({ ...entry, id: uid() })]
        return entry.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const updateEntry = useCallback(
    (id: string, patch: Partial<Omit<CreditCardEntry, 'id'>>) => {
      setEntries((prev) => {
        const target = prev.find((entry) => entry.id === id)
        if (!target) return prev

        // Editar um lançamento gerado automaticamente o torna manual,
        // para a edição não ser descartada na próxima sincronização.
        const effectivePatch =
          target.cycle === 'next' && target.autoGenerated
            ? { ...patch, autoGenerated: false }
            : patch
        const nextEntries = prev.map((entry) =>
          entry.id === id ? normalizeCreditCardEntry({ ...entry, ...effectivePatch }) : entry,
        )

        return target.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const removeEntry = useCallback(
    (id: string) => {
      setEntries((prev) => {
        const target = prev.find((entry) => entry.id === id)
        const nextEntries = prev.filter((entry) => entry.id !== id)
        return target?.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const replaceEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      setEntries((prev) => {
        const nextEntries = [
          ...prev.filter((entry) => entry.cycle !== cycle),
          ...incoming.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const appendEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      setEntries((prev) => {
        const nextEntries = [
          ...prev,
          ...incoming.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const anticipateInstallments = useCallback(
    (id: string, count: number) => {
      setEntries((prev) => {
        const entry = prev.find((item) => item.id === id)
        if (
          !entry ||
          entry.cycle !== 'current' ||
          !entry.installmentCurrent ||
          !entry.installmentTotal
        ) {
          return prev
        }

        const current = entry.installmentCurrent
        const total = entry.installmentTotal
        const quantity = Math.min(Math.max(1, Math.floor(count)), total - current)
        if (quantity < 1) return prev

        // Cada parcela antecipada vira um lançamento próprio na fatura atual;
        // o valor restante da compra fica concentrado na última parcela lançada.
        const anticipated = Array.from({ length: quantity }, (_, index) => {
          const installment = current + index + 1
          return normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            installmentCurrent: installment,
            remainingAmount:
              installment === current + quantity
                ? buildRemainingInstallmentsAmount(entry.amount, installment, total)
                : 0,
          })
        })

        return syncGeneratedNextEntries([
          ...prev.map((item) => (item.id === id ? { ...item, remainingAmount: 0 } : item)),
          ...anticipated,
        ])
      })
    },
    [setEntries],
  )

  const payInvoice = useCallback(() => {
    setEntries((prev) => {
      // Sincroniza antes de virar o ciclo: dados criados antes da geração
      // automática podem ainda não ter as parcelas materializadas na próxima.
      const syncedEntries = syncGeneratedNextEntries(prev)
      const newCurrentEntries = syncedEntries
        .filter((entry) => entry.cycle === 'next')
        .map((entry) =>
          normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            cycle: 'current',
            autoGenerated: false,
            sourceEntryId: undefined,
          }),
        )

      return syncGeneratedNextEntries(newCurrentEntries)
    })
    setSettingsRaw((prev) => advanceCreditCardSettingsCycle(normalizeCreditCardSettings(prev)))
  }, [setEntries, setSettingsRaw])

  const setSettings = useCallback(
    (next: CreditCardSettings) => {
      setSettingsRaw(normalizeCreditCardSettings(next))
    },
    [setSettingsRaw],
  )

  const addAccount = useCallback(
    (input: { name: string; closingDay: number; dueDay: number; limit?: number }) => {
      const trimmed = input.name.trim()
      if (!trimmed) return
      setStoredAccounts((prev) => [
        ...(Array.isArray(prev) ? prev : []),
        normalizeCardAccount({ ...input, name: trimmed, id: uid() }),
      ])
    },
    [setStoredAccounts],
  )

  const updateAccount = useCallback(
    (id: string, patch: Partial<Omit<CreditCardAccount, 'id'>>) => {
      setStoredAccounts((prev) =>
        prev.map((account) =>
          account.id === id ? normalizeCardAccount({ ...account, ...patch }) : account,
        ),
      )
    },
    [setStoredAccounts],
  )

  const removeAccount = useCallback(
    (id: string) => setStoredAccounts((prev) => prev.filter((account) => account.id !== id)),
    [setStoredAccounts],
  )

  const summary = useMemo(() => calculateCreditCardSummary(entries, settings), [entries, settings])
  const cycles = useMemo(() => describeCardCycles(accounts, summary), [accounts, summary])
  const unregistered = useMemo(() => unregisteredCardNames(entries, accounts), [entries, accounts])

  return {
    entries,
    settings,
    accounts,
    cycles,
    unregistered,
    summary,
    addAccount,
    updateAccount,
    removeAccount,
    addEntry,
    updateEntry,
    removeEntry,
    replaceEntries,
    appendEntries,
    anticipateInstallments,
    payInvoice,
    setSettings,
  }
}
