import { useCallback, useEffect, useMemo, useRef } from 'react'
import { useLocalStorage } from './useLocalStorage'
import type { CreditCardCycle, CreditCardEntry, CreditCardSettings } from '../types'
import {
  buildRemainingInstallmentsAmount,
  calculateCreditCardSummary,
  normalizeCreditCardEntry,
  syncGeneratedNextEntries,
} from '../lib/creditCards'
import { uid } from '../lib/shared'

const ENTRIES_STORAGE_KEY = 'uf_credit_card_entries_v1'
const SETTINGS_STORAGE_KEY = 'uf_credit_card_settings_v1'
const DEFAULT_SETTINGS: CreditCardSettings = { paymentDate: '05/07', personalSpendingLimit: 1500 }

export function useCreditCards() {
  const [storedEntries, setEntries] = useLocalStorage<CreditCardEntry[]>(ENTRIES_STORAGE_KEY, [])
  const entries = useMemo(
    () => (Array.isArray(storedEntries) ? storedEntries.map(normalizeCreditCardEntry) : []),
    [storedEntries],
  )
  const [settings, setSettingsRaw] = useLocalStorage<CreditCardSettings>(
    SETTINGS_STORAGE_KEY,
    DEFAULT_SETTINGS,
  )

  // A geração da próxima fatura roda a cada mutação, mas dados que chegam
  // prontos (backup importado, outro dispositivo) nunca passaram por uma:
  // sem isto, assinaturas e parcelas só apareceriam na próxima edição.
  const syncedOnMount = useRef(false)
  useEffect(() => {
    if (syncedOnMount.current || entries.length === 0) return
    syncedOnMount.current = true
    setEntries((prev) => {
      const synced = syncGeneratedNextEntries(prev.map(normalizeCreditCardEntry))
      return synced.length === prev.length ? prev : synced
    })
  }, [entries.length, setEntries])

  const addEntry = useCallback(
    (entry: Omit<CreditCardEntry, 'id'>) => {
      setEntries((prev) => {
        const nextEntries = [...prev, normalizeCreditCardEntry({ ...entry, id: uid() })]
        return entry.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const updateEntry = useCallback(
    (id: string, patch: Partial<Omit<CreditCardEntry, 'id'>>) => {
      setEntries((prev) => {
        const target = prev.find((entry) => entry.id === id)
        if (!target) return prev

        // Editar um lançamento gerado automaticamente o torna manual,
        // para a edição não ser descartada na próxima sincronização.
        const effectivePatch =
          target.cycle === 'next' && target.autoGenerated
            ? { ...patch, autoGenerated: false }
            : patch
        const nextEntries = prev.map((entry) =>
          entry.id === id ? normalizeCreditCardEntry({ ...entry, ...effectivePatch }) : entry,
        )

        return target.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const removeEntry = useCallback(
    (id: string) => {
      setEntries((prev) => {
        const target = prev.find((entry) => entry.id === id)
        const nextEntries = prev.filter((entry) => entry.id !== id)
        return target?.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const replaceEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      setEntries((prev) => {
        const nextEntries = [
          ...prev.filter((entry) => entry.cycle !== cycle),
          ...incoming.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const appendEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      setEntries((prev) => {
        const nextEntries = [
          ...prev,
          ...incoming.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries
      })
    },
    [setEntries],
  )

  const anticipateInstallments = useCallback(
    (id: string, count: number) => {
      setEntries((prev) => {
        const entry = prev.find((item) => item.id === id)
        if (
          !entry ||
          entry.cycle !== 'current' ||
          !entry.installmentCurrent ||
          !entry.installmentTotal
        ) {
          return prev
        }

        const current = entry.installmentCurrent
        const total = entry.installmentTotal
        const quantity = Math.min(Math.max(1, Math.floor(count)), total - current)
        if (quantity < 1) return prev

        // Cada parcela antecipada vira um lançamento próprio na fatura atual;
        // o valor restante da compra fica concentrado na última parcela lançada.
        const anticipated = Array.from({ length: quantity }, (_, index) => {
          const installment = current + index + 1
          return normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            installmentCurrent: installment,
            remainingAmount:
              installment === current + quantity
                ? buildRemainingInstallmentsAmount(entry.amount, installment, total)
                : 0,
          })
        })

        return syncGeneratedNextEntries([
          ...prev.map((item) => (item.id === id ? { ...item, remainingAmount: 0 } : item)),
          ...anticipated,
        ])
      })
    },
    [setEntries],
  )

  const payInvoice = useCallback(() => {
    setEntries((prev) => {
      // Sincroniza antes de virar o ciclo: dados criados antes da geração
      // automática podem ainda não ter as parcelas materializadas na próxima.
      const syncedEntries = syncGeneratedNextEntries(prev)
      const newCurrentEntries = syncedEntries
        .filter((entry) => entry.cycle === 'next')
        .map((entry) =>
          normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            cycle: 'current',
            autoGenerated: false,
            sourceEntryId: undefined,
          }),
        )

      return syncGeneratedNextEntries(newCurrentEntries)
    })
  }, [setEntries])

  const setSettings = useCallback(
    (next: CreditCardSettings) => {
      setSettingsRaw({ ...next, personalSpendingLimit: Math.max(0, next.personalSpendingLimit) })
    },
    [setSettingsRaw],
  )

  const summary = useMemo(() => calculateCreditCardSummary(entries, settings), [entries, settings])

  return {
    entries,
    settings,
    summary,
    addEntry,
    updateEntry,
    removeEntry,
    replaceEntries,
    appendEntries,
    anticipateInstallments,
    payInvoice,
    setSettings,
  }
}
