import { useCallback, useEffect, useMemo } from 'react'
import { useLocalStorage } from './useLocalStorage'
import type {
  CostItem,
  WantItem,
  DeductionItem,
  DiversificationSlice,
  CostCategory,
  DeductionType,
  BudgetArea,
  BudgetBucket,
  CreditCardCycle,
  CreditCardEntry,
  CreditCardSettings,
  CreditCardSummary,
  EmergencyFundState,
  SalaryInputMode,
  FinanceScenario,
  FinanceScenarioData,
  ScenarioSummary,
} from '../types'
import { BUDGET_MODELS, DEFAULT_DIVERSIFICATION, INVESTMENT_DEDUCTION_TYPES } from '../types/constants'

const SCENARIOS_STORAGE_KEY = 'uf_scenarios_v3'
const ACTIVE_SCENARIO_STORAGE_KEY = 'uf_active_scenario_v3'
const LEGACY_SCENARIOS_KEY = 'uf_scenarios_v2'
const LEGACY_ACTIVE_SCENARIO_KEY = 'uf_active_scenario_v2'
const DEFAULT_EMERGENCY_FUND: EmergencyFundState = { current: 0, targetMonths: 6 }
const DEFAULT_CREDIT_CARD_SETTINGS: CreditCardSettings = {
  paymentDate: '05/07',
  personalSpendingLimit: 1500,
}

function uid(): string {
  return Math.random().toString(36).slice(2, 10)
}

function nowIso(): string {
  return new Date().toISOString()
}

function readJson<T>(key: string, fallback: T): T {
  try {
    const item = window.localStorage.getItem(key)
    return item ? (JSON.parse(item) as T) : fallback
  } catch {
    return fallback
  }
}

function finiteNumber(value: unknown, fallback = 0) {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback
}

// ---------------------------------------------------------------------------
// Cartões de crédito (inalterado)
// ---------------------------------------------------------------------------

function normalizeCreditCardEntry(entry: CreditCardEntry): CreditCardEntry {
  const amount = finiteNumber(entry.amount)
  const installmentCurrent = finiteNumber(entry.installmentCurrent)
  const installmentTotal = finiteNumber(entry.installmentTotal)

  return {
    id: entry.id || uid(),
    cycle: entry.cycle === 'next' ? 'next' : 'current',
    description: entry.description?.trim() || 'Lancamento sem descricao',
    purchaseDate: entry.purchaseDate?.trim() || '',
    cardName: entry.cardName?.trim() || 'Cartao',
    amount,
    personalAmount: finiteNumber(entry.personalAmount, amount),
    remainingAmount: finiteNumber(entry.remainingAmount),
    ownerName: entry.ownerName?.trim() || '',
    ownerNote: entry.ownerNote?.trim() || '',
    installmentCurrent: installmentCurrent > 0 ? installmentCurrent : undefined,
    installmentTotal: installmentTotal > 0 ? installmentTotal : undefined,
    isRecurring: entry.isRecurring === true ? true : undefined,
    autoGenerated: entry.autoGenerated === true ? true : undefined,
    sourceEntryId: entry.sourceEntryId || undefined,
  }
}

function buildRemainingInstallmentsAmount(amount: number, current?: number, total?: number) {
  if (!current || !total || current >= total) return 0
  return amount * (total - current)
}

function creditCardPurchaseKey(entry: CreditCardEntry) {
  const normalize = (value: string) =>
    value
      .normalize('NFD')
      .replace(/\p{Diacritic}/gu, '')
      .toLowerCase()
      .trim()

  return `${normalize(entry.description)}|${normalize(entry.cardName)}`
}

// Recalcula os lançamentos gerados automaticamente da próxima fatura a partir
// da fatura atual: assinaturas recorrentes repetem e compras parceladas seguem
// para a parcela seguinte. Lançamentos manuais da próxima fatura são mantidos
// e bloqueiam a geração de duplicatas da mesma compra.
function syncGeneratedNextEntries(entries: CreditCardEntry[]): CreditCardEntry[] {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const manualNextEntries = entries.filter((entry) => entry.cycle === 'next' && !entry.autoGenerated)
  const manualNextKeys = new Set(manualNextEntries.map(creditCardPurchaseKey))
  const manualNextSourceIds = new Set(
    manualNextEntries.map((entry) => entry.sourceEntryId).filter(Boolean),
  )
  const isCoveredByManualEntry = (entry: CreditCardEntry) =>
    manualNextKeys.has(creditCardPurchaseKey(entry)) || manualNextSourceIds.has(entry.id)
  const generated: CreditCardEntry[] = []

  for (const entry of currentEntries) {
    if (!entry.isRecurring || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        remainingAmount: 0,
      }),
    )
  }

  const latestInstallments = new Map<string, CreditCardEntry>()
  for (const entry of currentEntries) {
    if (entry.isRecurring || !entry.installmentCurrent || !entry.installmentTotal) continue
    const key = `${creditCardPurchaseKey(entry)}|${entry.installmentTotal}`
    const existing = latestInstallments.get(key)
    if (!existing || entry.installmentCurrent > (existing.installmentCurrent ?? 0)) {
      latestInstallments.set(key, entry)
    }
  }

  for (const entry of latestInstallments.values()) {
    const nextInstallment = (entry.installmentCurrent ?? 0) + 1
    const total = entry.installmentTotal ?? 0
    if (nextInstallment > total || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        installmentCurrent: nextInstallment,
        remainingAmount: buildRemainingInstallmentsAmount(entry.amount, nextInstallment, total),
      }),
    )
  }

  return [...currentEntries, ...manualNextEntries, ...generated]
}

function calculateCreditCardSummary(
  entries: CreditCardEntry[],
  settings: CreditCardSettings,
): CreditCardSummary {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const nextEntries = entries.filter((entry) => entry.cycle === 'next')
  const currentTotal = currentEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalTotal = currentEntries.reduce((sum, entry) => sum + entry.personalAmount, 0)
  const currentThirdPartyTotal = currentEntries.reduce(
    (sum, entry) => sum + Math.max(0, entry.amount - entry.personalAmount),
    0,
  )
  const nextTotal = nextEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const nextPersonalTotal = nextEntries.reduce((sum, entry) => sum + entry.personalAmount, 0)
  const remainingInstallmentsTotal = currentEntries.reduce((sum, entry) => sum + entry.remainingAmount, 0)
  const remainingPersonalInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + (entry.personalAmount / (entry.amount || 1)) * entry.remainingAmount,
    0,
  )
  const byCard = new Map<string, { totalAmount: number; personalAmount: number }>()
  const byOwner = new Map<string, { totalAmount: number; personalAmount: number }>()

  for (const entry of currentEntries) {
    const existing = byCard.get(entry.cardName) ?? { totalAmount: 0, personalAmount: 0 }
    byCard.set(entry.cardName, {
      totalAmount: existing.totalAmount + entry.amount,
      personalAmount: existing.personalAmount + entry.personalAmount,
    })

    const thirdPartyAmount = Math.max(0, entry.amount - entry.personalAmount)
    if (thirdPartyAmount > 0) {
      const owner = entry.ownerName || entry.ownerNote || 'Outro'
      const ownerExisting = byOwner.get(owner) ?? { totalAmount: 0, personalAmount: 0 }
      byOwner.set(owner, {
        totalAmount: ownerExisting.totalAmount + thirdPartyAmount,
        personalAmount: ownerExisting.personalAmount,
      })
    }
  }

  return {
    currentTotal,
    currentPersonalTotal,
    currentThirdPartyTotal,
    nextTotal,
    nextPersonalTotal,
    remainingInstallmentsTotal,
    remainingPersonalInstallmentsTotal,
    availablePersonalLimit: settings.personalSpendingLimit - currentPersonalTotal,
    totalsByCard: Array.from(byCard.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    totalsByOwner: Array.from(byOwner.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    currentEntriesCount: currentEntries.length,
    nextEntriesCount: nextEntries.length,
  }
}

// ---------------------------------------------------------------------------
// Normalização e migração
// ---------------------------------------------------------------------------

function normalizeScenario(scenario: FinanceScenario): FinanceScenario {
  return {
    ...scenario,
    salaryNet: finiteNumber(scenario.salaryNet),
    salaryInputMode: scenario.salaryInputMode === 'take_home' ? 'take_home' : 'before_payroll_deductions',
    costs: Array.isArray(scenario.costs) ? scenario.costs : [],
    wants: Array.isArray(scenario.wants)
      ? scenario.wants.map((want) => ({
          id: want.id || uid(),
          name: want.name || 'Desejo',
          plannedAmount: Math.max(0, finiteNumber(want.plannedAmount)),
        }))
      : [],
    deductions: Array.isArray(scenario.deductions)
      ? scenario.deductions.map((deduction) => ({
          ...deduction,
          value: finiteNumber(deduction.value),
          employerContribution: finiteNumber(deduction.employerContribution),
        }))
      : [],
    selectedModelId: BUDGET_MODELS.some((m) => m.id === scenario.selectedModelId)
      ? scenario.selectedModelId
      : '50-30-20',
    diversification: Array.isArray(scenario.diversification)
      ? scenario.diversification
      : DEFAULT_DIVERSIFICATION,
    customModel: scenario.customModel ?? { n: 50, d: 30, i: 20 },
    emergencyFund: {
      current: Math.max(0, finiteNumber(scenario.emergencyFund?.current)),
      targetMonths: Math.max(1, Math.round(finiteNumber(scenario.emergencyFund?.targetMonths, 6))),
    },
    creditCardEntries: Array.isArray(scenario.creditCardEntries)
      ? scenario.creditCardEntries.map(normalizeCreditCardEntry)
      : [],
    creditCardSettings: {
      ...DEFAULT_CREDIT_CARD_SETTINGS,
      ...(scenario.creditCardSettings ?? {}),
      personalSpendingLimit: finiteNumber(
        scenario.creditCardSettings?.personalSpendingLimit,
        DEFAULT_CREDIT_CARD_SETTINGS.personalSpendingLimit,
      ),
    },
  }
}

function createDefaultScenario(name = 'Atual'): FinanceScenario {
  const timestamp = nowIso()

  return {
    id: uid(),
    name,
    createdAt: timestamp,
    updatedAt: timestamp,
    salaryNet: 0,
    salaryInputMode: 'before_payroll_deductions',
    costs: [],
    wants: [],
    deductions: [],
    selectedModelId: '50-30-20',
    diversification: DEFAULT_DIVERSIFICATION,
    customModel: { n: 50, d: 30, i: 20 },
    emergencyFund: DEFAULT_EMERGENCY_FUND,
    creditCardEntries: [],
    creditCardSettings: DEFAULT_CREDIT_CARD_SETTINGS,
  }
}

// Formato dos cenários v2, usado apenas na migração
interface LegacyWantItem {
  id: string
  name: string
  mode?: 'percentage' | 'fixed'
  percentage?: number
  fixedAmount?: number
}

interface LegacyAllocationTransfer {
  from: BudgetArea
  to: BudgetArea
  amount: number
}

interface LegacyScenario {
  id?: string
  name?: string
  createdAt?: string
  updatedAt?: string
  salaryNet?: number
  salaryInputMode?: SalaryInputMode
  costs?: CostItem[]
  wants?: LegacyWantItem[]
  deductions?: DeductionItem[]
  selectedModelId?: string
  diversification?: DiversificationSlice[]
  customModel?: { n: number; d: number; i: number }
  allocationTransfers?: LegacyAllocationTransfer[]
  emergencyFundCurrent?: number
  creditCardEntries?: CreditCardEntry[]
  creditCardSettings?: CreditCardSettings
}

function resolveModelPercentages(selectedModelId?: string, customModel?: { n: number; d: number; i: number }) {
  const model = BUDGET_MODELS.find((m) => m.id === selectedModelId) ?? BUDGET_MODELS[0]
  if (model.id === 'custom' && customModel) {
    return { necessidades: customModel.n, desejos: customModel.d, investimentos: customModel.i }
  }
  return { necessidades: model.necessidades, desejos: model.desejos, investimentos: model.investimentos }
}

/**
 * Converte um cenário v2 para o v3. Desejos percentuais viram valores
 * planejados equivalentes ao que a fórmula antiga exibia (incluindo o efeito
 * das transferências de meta, que deixam de existir no v3).
 */
function convertLegacyScenario(legacy: LegacyScenario): FinanceScenario {
  const timestamp = nowIso()
  const salaryNet = finiteNumber(legacy.salaryNet)
  const salaryInputMode: SalaryInputMode =
    legacy.salaryInputMode === 'take_home' ? 'take_home' : 'before_payroll_deductions'
  const deductions = Array.isArray(legacy.deductions) ? legacy.deductions : []
  const totalDeductions = deductions.reduce((sum, d) => sum + finiteNumber(d.value), 0)
  const investmentDeductions = deductions
    .filter((d) => INVESTMENT_DEDUCTION_TYPES.includes(d.type))
    .reduce((sum, d) => sum + finiteNumber(d.value), 0)
  const benefitDeductions = totalDeductions - investmentDeductions
  const availableForBudget =
    salaryInputMode === 'before_payroll_deductions'
      ? Math.max(0, salaryNet - benefitDeductions)
      : salaryNet + investmentDeductions

  const model = resolveModelPercentages(legacy.selectedModelId, legacy.customModel)
  const allocation: Record<BudgetArea, number> = {
    necessidades: (availableForBudget * model.necessidades) / 100,
    desejos: (availableForBudget * model.desejos) / 100,
    investimentos: (availableForBudget * model.investimentos) / 100,
  }

  for (const transfer of legacy.allocationTransfers ?? []) {
    if (!transfer || transfer.from === transfer.to) continue
    const amount = Math.min(finiteNumber(transfer.amount), allocation[transfer.from] ?? 0)
    if (amount <= 0) continue
    allocation[transfer.from] -= amount
    allocation[transfer.to] += amount
  }

  const legacyWants = Array.isArray(legacy.wants) ? legacy.wants : []
  const fixedWantsAmount = legacyWants
    .filter((w) => w.mode === 'fixed')
    .reduce((sum, w) => sum + finiteNumber(w.fixedAmount), 0)
  const variableWantsBase = Math.max(0, allocation.desejos - fixedWantsAmount)

  const wants: WantItem[] = legacyWants.map((want) => ({
    id: want.id || uid(),
    name: want.name || 'Desejo',
    plannedAmount:
      want.mode === 'fixed'
        ? Math.max(0, finiteNumber(want.fixedAmount))
        : Math.round(variableWantsBase * finiteNumber(want.percentage)) / 100,
  }))

  return normalizeScenario({
    id: legacy.id || uid(),
    name: legacy.name || 'Atual',
    createdAt: legacy.createdAt || timestamp,
    updatedAt: timestamp,
    salaryNet,
    salaryInputMode,
    costs: Array.isArray(legacy.costs) ? legacy.costs : [],
    wants,
    deductions,
    selectedModelId: legacy.selectedModelId || '50-30-20',
    diversification: Array.isArray(legacy.diversification) ? legacy.diversification : DEFAULT_DIVERSIFICATION,
    customModel: legacy.customModel ?? { n: 50, d: 30, i: 20 },
    emergencyFund: { current: finiteNumber(legacy.emergencyFundCurrent), targetMonths: 6 },
    creditCardEntries: Array.isArray(legacy.creditCardEntries) ? legacy.creditCardEntries : [],
    creditCardSettings: legacy.creditCardSettings ?? DEFAULT_CREDIT_CARD_SETTINGS,
  })
}

function loadInitialScenarios(): FinanceScenario[] {
  const existing = readJson<FinanceScenario[] | null>(SCENARIOS_STORAGE_KEY, null)
  if (existing?.length) return existing.map(normalizeScenario)

  const legacy = readJson<LegacyScenario[] | null>(LEGACY_SCENARIOS_KEY, null)
  if (legacy?.length) return legacy.map(convertLegacyScenario)

  return [createDefaultScenario('Atual')]
}

function loadInitialActiveScenarioId(scenarios: FinanceScenario[]): string {
  const stored = readJson<string>(ACTIVE_SCENARIO_STORAGE_KEY, '')
  if (scenarios.some((scenario) => scenario.id === stored)) return stored
  const legacyActive = readJson<string>(LEGACY_ACTIVE_SCENARIO_KEY, '')
  if (scenarios.some((scenario) => scenario.id === legacyActive)) return legacyActive
  return scenarios[0]?.id ?? ''
}

function cloneScenario(source: FinanceScenario, name: string): FinanceScenario {
  const timestamp = nowIso()

  return {
    ...structuredClone(source),
    id: uid(),
    name,
    createdAt: timestamp,
    updatedAt: timestamp,
  }
}

// ---------------------------------------------------------------------------
// Cálculo do cenário
// ---------------------------------------------------------------------------

function getSelectedModel(state: FinanceScenarioData) {
  const model = BUDGET_MODELS.find((m) => m.id === state.selectedModelId) ?? BUDGET_MODELS[0]
  if (model.id === 'custom') {
    return {
      ...model,
      necessidades: state.customModel.n,
      desejos: state.customModel.d,
      investimentos: state.customModel.i,
    }
  }
  return model
}

function isFixedIncomeSlice(name: string) {
  const normalized = name
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()

  return (
    normalized.includes('renda fixa') ||
    normalized.includes('tesouro') ||
    normalized.includes('selic') ||
    normalized.includes('cdb') ||
    normalized.includes('poupanca') ||
    normalized.includes('liquidez')
  )
}

function buildBucket(target: number, actual: number): BudgetBucket {
  return {
    target,
    actual,
    diff: target - actual,
    percentage: target > 0 ? (actual / target) * 100 : 0,
  }
}

export type ScenarioMetrics = ReturnType<typeof calculateScenario>

function calculateScenario(state: FinanceScenario) {
  const selectedModel = getSelectedModel(state)
  const totalCosts = state.costs.reduce((sum, c) => sum + c.value, 0)
  const totalDeductions = state.deductions.reduce((sum, d) => sum + d.value, 0)
  const investmentDeductions = state.deductions
    .filter((d) => INVESTMENT_DEDUCTION_TYPES.includes(d.type))
    .reduce((sum, d) => sum + d.value, 0)
  const employerInvestmentContributions = state.deductions
    .filter((d) => INVESTMENT_DEDUCTION_TYPES.includes(d.type))
    .reduce((sum, d) => sum + (d.employerContribution ?? 0), 0)
  const benefitDeductions = totalDeductions - investmentDeductions

  // "Cai na conta": o que sobra do salário depois de toda a folha.
  const paycheckInAccount =
    state.salaryInputMode === 'before_payroll_deductions'
      ? Math.max(0, state.salaryNet - totalDeductions)
      : state.salaryNet

  // Base do orçamento: benefícios (VA, plano etc.) ficam fora porque não são
  // dinheiro livre; previdência descontada em folha continua contando, porque
  // é investimento seu.
  const availableForBudget =
    state.salaryInputMode === 'before_payroll_deductions'
      ? Math.max(0, state.salaryNet - benefitDeductions)
      : state.salaryNet + investmentDeductions

  const budgetAllocation: Record<BudgetArea, number> = {
    necessidades: (availableForBudget * selectedModel.necessidades) / 100,
    desejos: (availableForBudget * selectedModel.desejos) / 100,
    investimentos: (availableForBudget * selectedModel.investimentos) / 100,
  }

  const totalWantsAmount = state.wants.reduce((sum, w) => sum + w.plannedAmount, 0)

  // Quanto ainda precisa ser aportado pela conta, além do que já sai em folha.
  const directInvestmentTarget = Math.max(0, budgetAllocation.investimentos - investmentDeductions)
  const totalPlannedInvestment = investmentDeductions + directInvestmentTarget
  const savingsRate = availableForBudget > 0 ? (totalPlannedInvestment / availableForBudget) * 100 : 0

  // Saldo se o plano inteiro for executado: custos pagos, desejos gastos e
  // aporte direto feito por completo.
  const balanceAfterPlan = paycheckInAccount - totalCosts - totalWantsAmount - directInvestmentTarget

  const budgetComparison: Record<BudgetArea, BudgetBucket> = {
    necessidades: buildBucket(budgetAllocation.necessidades, totalCosts),
    desejos: buildBucket(budgetAllocation.desejos, totalWantsAmount),
    investimentos: buildBucket(budgetAllocation.investimentos, totalPlannedInvestment),
  }

  const totalDiversificationPercentage = state.diversification.reduce((sum, slice) => sum + slice.percentage, 0)
  const investmentAllocation = state.diversification.map((slice) => ({
    ...slice,
    amount: (directInvestmentTarget * slice.percentage) / 100,
  }))
  const fixedIncomeMonthlyAllocation = investmentAllocation
    .filter((slice) => isFixedIncomeSlice(slice.name))
    .reduce((sum, slice) => sum + slice.amount, 0)

  const costsByCategory = new Map<CostCategory, number>()
  for (const c of state.costs) {
    costsByCategory.set(c.category, (costsByCategory.get(c.category) || 0) + c.value)
  }

  const emergencyFundTarget = totalCosts * state.emergencyFund.targetMonths
  const emergencyFundRemaining = Math.max(0, emergencyFundTarget - state.emergencyFund.current)
  const emergencyFundProgress =
    emergencyFundTarget > 0 ? Math.min(100, (state.emergencyFund.current / emergencyFundTarget) * 100) : 0
  const emergencyFundMonthsToGoal =
    emergencyFundRemaining > 0 && fixedIncomeMonthlyAllocation > 0
      ? Math.ceil(emergencyFundRemaining / fixedIncomeMonthlyAllocation)
      : 0

  const creditCardSummary = calculateCreditCardSummary(state.creditCardEntries, state.creditCardSettings)

  return {
    selectedModel,
    totalCosts,
    totalDeductions,
    investmentDeductions,
    employerInvestmentContributions,
    benefitDeductions,
    paycheckInAccount,
    availableForBudget,
    budgetAllocation,
    totalWantsAmount,
    directInvestmentTarget,
    totalPlannedInvestment,
    savingsRate,
    balanceAfterPlan,
    budgetComparison,
    totalDiversificationPercentage,
    investmentAllocation,
    fixedIncomeMonthlyAllocation,
    costsByCategory,
    emergencyFundTarget,
    emergencyFundRemaining,
    emergencyFundProgress,
    emergencyFundMonthsToGoal,
    creditCardSummary,
  }
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useFinancas() {
  const [storedScenarios, setScenarios] = useLocalStorage<FinanceScenario[]>(
    SCENARIOS_STORAGE_KEY,
    loadInitialScenarios(),
  )
  const scenarios = useMemo(
    () => (Array.isArray(storedScenarios) ? storedScenarios.map(normalizeScenario) : []),
    [storedScenarios],
  )
  const [activeScenarioId, setActiveScenarioId] = useLocalStorage<string>(
    ACTIVE_SCENARIO_STORAGE_KEY,
    loadInitialActiveScenarioId(scenarios),
  )

  useEffect(() => {
    if (scenarios.length === 0) {
      const scenario = createDefaultScenario('Atual')
      setScenarios([scenario])
      setActiveScenarioId(scenario.id)
      return
    }

    if (!scenarios.some((scenario) => scenario.id === activeScenarioId)) {
      setActiveScenarioId(scenarios[0].id)
    }
  }, [activeScenarioId, scenarios, setActiveScenarioId, setScenarios])

  const activeScenario =
    scenarios.find((scenario) => scenario.id === activeScenarioId) ?? scenarios[0] ?? createDefaultScenario('Atual')
  const activeId = activeScenario?.id ?? ''

  const updateActiveScenario = useCallback(
    (updater: (scenario: FinanceScenario) => FinanceScenario) => {
      setScenarios((prev) =>
        prev.map((scenario) =>
          scenario.id === activeId
            ? { ...updater(normalizeScenario(scenario)), updatedAt: nowIso() }
            : scenario,
        ),
      )
    },
    [activeId, setScenarios],
  )

  const setScenarioField = useCallback(
    <K extends keyof FinanceScenarioData>(field: K, value: FinanceScenarioData[K]) => {
      updateActiveScenario((scenario) => ({ ...scenario, [field]: value }))
    },
    [updateActiveScenario],
  )

  // Cenários
  const createScenario = useCallback(
    (name = `Cenário ${scenarios.length + 1}`) => {
      const scenario = createDefaultScenario(name)
      setScenarios((prev) => [...prev, scenario])
      setActiveScenarioId(scenario.id)
    },
    [scenarios.length, setActiveScenarioId, setScenarios],
  )

  const duplicateScenario = useCallback(
    (sourceId = activeId) => {
      const source = scenarios.find((scenario) => scenario.id === sourceId) ?? activeScenario
      if (!source) return
      const scenario = cloneScenario(source, `${source.name} (cópia)`)
      setScenarios((prev) => [...prev, scenario])
      setActiveScenarioId(scenario.id)
    },
    [activeId, activeScenario, scenarios, setActiveScenarioId, setScenarios],
  )

  const renameScenario = useCallback(
    (id: string, name: string) => {
      const trimmed = name.trim()
      if (!trimmed) return
      setScenarios((prev) =>
        prev.map((scenario) =>
          scenario.id === id ? { ...scenario, name: trimmed, updatedAt: nowIso() } : scenario,
        ),
      )
    },
    [setScenarios],
  )

  const removeScenario = useCallback(
    (id: string) => {
      if (scenarios.length <= 1) return
      const remaining = scenarios.filter((scenario) => scenario.id !== id)
      setScenarios(remaining)
      if (id === activeId) {
        setActiveScenarioId(remaining[0]?.id ?? '')
      }
    },
    [activeId, scenarios, setActiveScenarioId, setScenarios],
  )

  // Custos
  const addCost = useCallback(
    (name: string, value: number, category: CostCategory) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        costs: [...scenario.costs, { id: uid(), name, value, category }],
      }))
    },
    [updateActiveScenario],
  )

  const removeCost = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        costs: scenario.costs.filter((c) => c.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  // Desejos
  const addWant = useCallback(
    (name: string, plannedAmount = 0) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: [...scenario.wants, { id: uid(), name, plannedAmount: Math.max(0, plannedAmount) }],
      }))
    },
    [updateActiveScenario],
  )

  const removeWant = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.filter((w) => w.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const updateWantAmount = useCallback(
    (id: string, plannedAmount: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.map((w) =>
          w.id === id ? { ...w, plannedAmount: Math.max(0, plannedAmount) } : w,
        ),
      }))
    },
    [updateActiveScenario],
  )

  // Descontos em folha
  const addDeduction = useCallback(
    (name: string, value: number, type: DeductionType, employerContribution = 0) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: [...scenario.deductions, { id: uid(), name, value, type, employerContribution }],
      }))
    },
    [updateActiveScenario],
  )

  const removeDeduction = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: scenario.deductions.filter((d) => d.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const updateDeductionEmployerContribution = useCallback(
    (id: string, employerContribution: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: scenario.deductions.map((d) =>
          d.id === id ? { ...d, employerContribution: Math.max(0, employerContribution) } : d,
        ),
      }))
    },
    [updateActiveScenario],
  )

  // Diversificação
  const updateDiversification = useCallback(
    (slices: DiversificationSlice[]) => {
      setScenarioField('diversification', slices)
    },
    [setScenarioField],
  )

  const addDiversificationSlice = useCallback(
    (name: string, percentage: number, color: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        diversification: [...scenario.diversification, { id: uid(), name, percentage, color }],
      }))
    },
    [updateActiveScenario],
  )

  const removeDiversificationSlice = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        diversification: scenario.diversification.filter((s) => s.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  // Reserva de emergência
  const setEmergencyFundCurrent = useCallback(
    (value: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        emergencyFund: { ...scenario.emergencyFund, current: Math.max(0, value) },
      }))
    },
    [updateActiveScenario],
  )

  const setEmergencyFundTargetMonths = useCallback(
    (months: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        emergencyFund: { ...scenario.emergencyFund, targetMonths: Math.max(1, Math.round(months)) },
      }))
    },
    [updateActiveScenario],
  )

  // Cartões de crédito (inalterado)
  const addCreditCardEntry = useCallback(
    (entry: Omit<CreditCardEntry, 'id'>) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [...scenario.creditCardEntries, normalizeCreditCardEntry({ ...entry, id: uid() })]
        return {
          ...scenario,
          creditCardEntries: entry.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const updateCreditCardEntry = useCallback(
    (id: string, patch: Partial<Omit<CreditCardEntry, 'id'>>) => {
      updateActiveScenario((scenario) => {
        const target = scenario.creditCardEntries.find((entry) => entry.id === id)
        if (!target) return scenario

        // Editar um lançamento gerado automaticamente o torna manual,
        // para a edição não ser descartada na próxima sincronização.
        const effectivePatch =
          target.cycle === 'next' && target.autoGenerated ? { ...patch, autoGenerated: false } : patch
        const nextEntries = scenario.creditCardEntries.map((entry) =>
          entry.id === id ? normalizeCreditCardEntry({ ...entry, ...effectivePatch }) : entry,
        )

        return {
          ...scenario,
          creditCardEntries: target.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const removeCreditCardEntry = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => {
        const target = scenario.creditCardEntries.find((entry) => entry.id === id)
        const nextEntries = scenario.creditCardEntries.filter((entry) => entry.id !== id)
        return {
          ...scenario,
          creditCardEntries: target?.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const replaceCreditCardEntries = useCallback(
    (cycle: CreditCardCycle, entries: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [
          ...scenario.creditCardEntries.filter((entry) => entry.cycle !== cycle),
          ...entries.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return {
          ...scenario,
          creditCardEntries: cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const appendCreditCardEntries = useCallback(
    (cycle: CreditCardCycle, entries: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [
          ...scenario.creditCardEntries,
          ...entries.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return {
          ...scenario,
          creditCardEntries: cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const anticipateCreditCardInstallments = useCallback(
    (id: string, count: number) => {
      updateActiveScenario((scenario) => {
        const entry = scenario.creditCardEntries.find((item) => item.id === id)
        if (!entry || entry.cycle !== 'current' || !entry.installmentCurrent || !entry.installmentTotal) {
          return scenario
        }

        const current = entry.installmentCurrent
        const total = entry.installmentTotal
        const quantity = Math.min(Math.max(1, Math.floor(count)), total - current)
        if (quantity < 1) return scenario

        // Cada parcela antecipada vira um lançamento próprio na fatura atual;
        // o valor restante da compra fica concentrado na última parcela lançada.
        const anticipated = Array.from({ length: quantity }, (_, index) => {
          const installment = current + index + 1
          return normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            installmentCurrent: installment,
            remainingAmount:
              installment === current + quantity
                ? buildRemainingInstallmentsAmount(entry.amount, installment, total)
                : 0,
          })
        })

        const nextEntries = [
          ...scenario.creditCardEntries.map((item) => (item.id === id ? { ...item, remainingAmount: 0 } : item)),
          ...anticipated,
        ]

        return { ...scenario, creditCardEntries: syncGeneratedNextEntries(nextEntries) }
      })
    },
    [updateActiveScenario],
  )

  const payCreditCardInvoice = useCallback(() => {
    updateActiveScenario((scenario) => {
      // Sincroniza antes de virar o ciclo: dados criados antes da geração
      // automática podem ainda não ter as parcelas materializadas na próxima.
      const syncedEntries = syncGeneratedNextEntries(scenario.creditCardEntries)
      const newCurrentEntries = syncedEntries
        .filter((entry) => entry.cycle === 'next')
        .map((entry) =>
          normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            cycle: 'current',
            autoGenerated: false,
            sourceEntryId: undefined,
          }),
        )

      return { ...scenario, creditCardEntries: syncGeneratedNextEntries(newCurrentEntries) }
    })
  }, [updateActiveScenario])

  const setCreditCardSettings = useCallback(
    (settings: CreditCardSettings) => {
      setScenarioField('creditCardSettings', {
        ...settings,
        personalSpendingLimit: Math.max(0, settings.personalSpendingLimit),
      })
    },
    [setScenarioField],
  )

  const metrics = useMemo(() => calculateScenario(activeScenario), [activeScenario])

  const scenarioSummaries = useMemo<ScenarioSummary[]>(
    () =>
      scenarios.map((scenario) => {
        const summary = calculateScenario(scenario)
        return {
          id: scenario.id,
          name: scenario.name,
          availableForBudget: summary.availableForBudget,
          totalCosts: summary.totalCosts,
          totalWantsAmount: summary.totalWantsAmount,
          totalPlannedInvestment: summary.totalPlannedInvestment,
          balanceAfterPlan: summary.balanceAfterPlan,
          savingsRate: summary.savingsRate,
        }
      }),
    [scenarios],
  )

  return {
    // Cenários
    scenarios,
    activeScenario,
    activeScenarioId: activeId,
    setActiveScenarioId,
    createScenario,
    duplicateScenario,
    renameScenario,
    removeScenario,
    scenarioSummaries,

    // Estado bruto do cenário ativo
    salaryNet: activeScenario.salaryNet,
    setSalaryNet: (value: number) => setScenarioField('salaryNet', value),
    salaryInputMode: activeScenario.salaryInputMode,
    setSalaryInputMode: (mode: SalaryInputMode) => setScenarioField('salaryInputMode', mode),
    costs: activeScenario.costs,
    addCost,
    removeCost,
    wants: activeScenario.wants,
    addWant,
    removeWant,
    updateWantAmount,
    deductions: activeScenario.deductions,
    addDeduction,
    removeDeduction,
    updateDeductionEmployerContribution,
    selectedModelId: activeScenario.selectedModelId,
    setSelectedModelId: (id: string) => setScenarioField('selectedModelId', id),
    customModel: activeScenario.customModel,
    setCustomModel: (model: { n: number; d: number; i: number }) => setScenarioField('customModel', model),
    diversification: activeScenario.diversification,
    updateDiversification,
    addDiversificationSlice,
    removeDiversificationSlice,
    emergencyFund: activeScenario.emergencyFund,
    setEmergencyFundCurrent,
    setEmergencyFundTargetMonths,

    // Métricas calculadas
    metrics,

    // Cartões de crédito
    creditCardEntries: activeScenario.creditCardEntries,
    creditCardSettings: activeScenario.creditCardSettings,
    creditCardSummary: metrics.creditCardSummary,
    addCreditCardEntry,
    updateCreditCardEntry,
    removeCreditCardEntry,
    replaceCreditCardEntries,
    appendCreditCardEntries,
    anticipateCreditCardInstallments,
    payCreditCardInvoice,
    setCreditCardSettings,
  }
}
