import { useCallback, useEffect, useMemo } from 'react'
import { useLocalStorage } from './useLocalStorage'
import type {
  CostItem,
  WantItem,
  DeductionItem,
  DiversificationSlice,
  CostCategory,
  DeductionType,
  BudgetBucket,
  BudgetArea,
  AllocationTransfer,
  CreditCardCycle,
  CreditCardEntry,
  CreditCardSettings,
  CreditCardSummary,
  SalaryInputMode,
  FinanceScenario,
  FinanceScenarioData,
  ScenarioSummary,
} from '../types'
import { BUDGET_MODELS, DEFAULT_DIVERSIFICATION, INVESTMENT_DEDUCTION_TYPES } from '../types/constants'

const SCENARIOS_STORAGE_KEY = 'uf_scenarios_v2'
const ACTIVE_SCENARIO_STORAGE_KEY = 'uf_active_scenario_v2'
const BUDGET_AREAS: BudgetArea[] = ['necessidades', 'desejos', 'investimentos']
const DEFAULT_CREDIT_CARD_SETTINGS: CreditCardSettings = {
  paymentDate: '05/07',
  personalSpendingLimit: 1500,
}

function uid(): string {
  return Math.random().toString(36).slice(2, 10)
}

function nowIso(): string {
  return new Date().toISOString()
}

function readJson<T>(key: string, fallback: T): T {
  try {
    const item = window.localStorage.getItem(key)
    return item ? (JSON.parse(item) as T) : fallback
  } catch {
    return fallback
  }
}

function finiteNumber(value: unknown, fallback = 0) {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback
}

function normalizeCreditCardEntry(entry: CreditCardEntry): CreditCardEntry {
  const amount = finiteNumber(entry.amount)
  const installmentCurrent = finiteNumber(entry.installmentCurrent)
  const installmentTotal = finiteNumber(entry.installmentTotal)

  return {
    id: entry.id || uid(),
    cycle: entry.cycle === 'next' ? 'next' : 'current',
    description: entry.description?.trim() || 'Lancamento sem descricao',
    purchaseDate: entry.purchaseDate?.trim() || '',
    cardName: entry.cardName?.trim() || 'Cartao',
    amount,
    personalAmount: finiteNumber(entry.personalAmount, amount),
    remainingAmount: finiteNumber(entry.remainingAmount),
    ownerName: entry.ownerName?.trim() || '',
    ownerNote: entry.ownerNote?.trim() || '',
    installmentCurrent: installmentCurrent > 0 ? installmentCurrent : undefined,
    installmentTotal: installmentTotal > 0 ? installmentTotal : undefined,
    isRecurring: entry.isRecurring === true ? true : undefined,
    autoGenerated: entry.autoGenerated === true ? true : undefined,
    sourceEntryId: entry.sourceEntryId || undefined,
  }
}

function buildRemainingInstallmentsAmount(amount: number, current?: number, total?: number) {
  if (!current || !total || current >= total) return 0
  return amount * (total - current)
}

function creditCardPurchaseKey(entry: CreditCardEntry) {
  const normalize = (value: string) =>
    value
      .normalize('NFD')
      .replace(/\p{Diacritic}/gu, '')
      .toLowerCase()
      .trim()

  return `${normalize(entry.description)}|${normalize(entry.cardName)}`
}

// Recalcula os lançamentos gerados automaticamente da próxima fatura a partir
// da fatura atual: assinaturas recorrentes repetem e compras parceladas seguem
// para a parcela seguinte. Lançamentos manuais da próxima fatura são mantidos
// e bloqueiam a geração de duplicatas da mesma compra.
function syncGeneratedNextEntries(entries: CreditCardEntry[]): CreditCardEntry[] {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const manualNextEntries = entries.filter((entry) => entry.cycle === 'next' && !entry.autoGenerated)
  const manualNextKeys = new Set(manualNextEntries.map(creditCardPurchaseKey))
  const manualNextSourceIds = new Set(
    manualNextEntries.map((entry) => entry.sourceEntryId).filter(Boolean),
  )
  const isCoveredByManualEntry = (entry: CreditCardEntry) =>
    manualNextKeys.has(creditCardPurchaseKey(entry)) || manualNextSourceIds.has(entry.id)
  const generated: CreditCardEntry[] = []

  for (const entry of currentEntries) {
    if (!entry.isRecurring || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        remainingAmount: 0,
      }),
    )
  }

  const latestInstallments = new Map<string, CreditCardEntry>()
  for (const entry of currentEntries) {
    if (entry.isRecurring || !entry.installmentCurrent || !entry.installmentTotal) continue
    const key = `${creditCardPurchaseKey(entry)}|${entry.installmentTotal}`
    const existing = latestInstallments.get(key)
    if (!existing || entry.installmentCurrent > (existing.installmentCurrent ?? 0)) {
      latestInstallments.set(key, entry)
    }
  }

  for (const entry of latestInstallments.values()) {
    const nextInstallment = (entry.installmentCurrent ?? 0) + 1
    const total = entry.installmentTotal ?? 0
    if (nextInstallment > total || isCoveredByManualEntry(entry)) continue
    generated.push(
      normalizeCreditCardEntry({
        ...entry,
        id: uid(),
        cycle: 'next',
        autoGenerated: true,
        sourceEntryId: entry.id,
        installmentCurrent: nextInstallment,
        remainingAmount: buildRemainingInstallmentsAmount(entry.amount, nextInstallment, total),
      }),
    )
  }

  return [...currentEntries, ...manualNextEntries, ...generated]
}

function normalizeScenario(scenario: FinanceScenario): FinanceScenario {
  return {
    ...scenario,
    salaryInputMode: scenario.salaryInputMode ?? 'before_payroll_deductions',
    costs: Array.isArray(scenario.costs) ? scenario.costs : [],
    wants: Array.isArray(scenario.wants)
      ? scenario.wants.map((want) => ({
          ...want,
          mode: want.mode ?? 'percentage',
          percentage: Number.isFinite(want.percentage) ? want.percentage : 0,
          fixedAmount: Number.isFinite(want.fixedAmount) ? want.fixedAmount : 0,
        }))
      : [],
    deductions: Array.isArray(scenario.deductions)
      ? scenario.deductions.map((deduction) => ({
          ...deduction,
          employerContribution: Number.isFinite(deduction.employerContribution)
            ? deduction.employerContribution
            : 0,
        }))
      : [],
    diversification: Array.isArray(scenario.diversification) ? scenario.diversification : DEFAULT_DIVERSIFICATION,
    customModel: scenario.customModel ?? { n: 50, d: 30, i: 20 },
    surplusToDesejos: Number.isFinite(scenario.surplusToDesejos) ? scenario.surplusToDesejos : 50,
    allocationTransfers: Array.isArray(scenario.allocationTransfers)
      ? scenario.allocationTransfers.filter(
          (transfer) =>
            BUDGET_AREAS.includes(transfer.from) &&
            BUDGET_AREAS.includes(transfer.to) &&
            transfer.from !== transfer.to &&
            transfer.amount > 0,
        )
      : [],
    emergencyFundCurrent: Number.isFinite(scenario.emergencyFundCurrent) ? scenario.emergencyFundCurrent : 0,
    creditCardEntries: Array.isArray(scenario.creditCardEntries)
      ? scenario.creditCardEntries.map(normalizeCreditCardEntry)
      : [],
    creditCardSettings: {
      ...DEFAULT_CREDIT_CARD_SETTINGS,
      ...(scenario.creditCardSettings ?? {}),
      personalSpendingLimit: finiteNumber(
        scenario.creditCardSettings?.personalSpendingLimit,
        DEFAULT_CREDIT_CARD_SETTINGS.personalSpendingLimit,
      ),
    },
  }
}

function createDefaultScenario(name = 'Atual'): FinanceScenario {
  const timestamp = nowIso()

  return {
    id: uid(),
    name,
    createdAt: timestamp,
    updatedAt: timestamp,
    salaryNet: 0,
    salaryInputMode: 'before_payroll_deductions',
    costs: [],
    wants: [],
    deductions: [],
    selectedModelId: '50-30-20',
    diversification: DEFAULT_DIVERSIFICATION,
    customModel: { n: 50, d: 30, i: 20 },
    surplusToDesejos: 50,
    allocationTransfers: [],
    emergencyFundCurrent: 0,
    creditCardEntries: [],
    creditCardSettings: DEFAULT_CREDIT_CARD_SETTINGS,
  }
}

function migrateLegacyScenario(): FinanceScenario {
  const timestamp = nowIso()

  return {
    id: uid(),
    name: 'Atual',
    createdAt: timestamp,
    updatedAt: timestamp,
    salaryNet: readJson<number>('uf_salary_net', 0),
    salaryInputMode: readJson<SalaryInputMode>('uf_salary_input_mode', 'before_payroll_deductions'),
    costs: readJson<CostItem[]>('uf_costs', []),
    wants: readJson<WantItem[]>('uf_wants', []),
    deductions: readJson<DeductionItem[]>('uf_deductions', []),
    selectedModelId: readJson<string>('uf_model', '50-30-20'),
    diversification: readJson<DiversificationSlice[]>('uf_diversification', DEFAULT_DIVERSIFICATION),
    customModel: readJson<{ n: number; d: number; i: number }>('uf_custom_model', { n: 50, d: 30, i: 20 }),
    surplusToDesejos: readJson<number>('uf_surplus_desejos', 50),
    allocationTransfers: [],
    emergencyFundCurrent: readJson<number>('uf_emergency_current', 0),
    creditCardEntries: readJson<CreditCardEntry[]>('uf_credit_card_entries', []),
    creditCardSettings: readJson<CreditCardSettings>('uf_credit_card_settings', DEFAULT_CREDIT_CARD_SETTINGS),
  }
}

function loadInitialScenarios(): FinanceScenario[] {
  const existing = readJson<FinanceScenario[] | null>(SCENARIOS_STORAGE_KEY, null)
  if (existing?.length) return existing.map(normalizeScenario)

  const legacyScenario = migrateLegacyScenario()
  const hasLegacyData =
    legacyScenario.salaryNet > 0 ||
    legacyScenario.costs.length > 0 ||
    legacyScenario.wants.length > 0 ||
    legacyScenario.deductions.length > 0

  return hasLegacyData ? [normalizeScenario(legacyScenario)] : [createDefaultScenario('Atual')]
}

function cloneScenario(source: FinanceScenario, name: string): FinanceScenario {
  const timestamp = nowIso()

  return {
    ...structuredClone(source),
    id: uid(),
    name,
    createdAt: timestamp,
    updatedAt: timestamp,
  }
}

function getSelectedModel(state: FinanceScenarioData) {
  const model = BUDGET_MODELS.find((m) => m.id === state.selectedModelId) ?? BUDGET_MODELS[0]
  if (model.id === 'custom') {
    return {
      ...model,
      necessidades: state.customModel.n,
      desejos: state.customModel.d,
      investimentos: state.customModel.i,
    }
  }
  return model
}

function applyAllocationTransfers(
  baseBudgetAllocation: Record<BudgetArea, number>,
  transfers: AllocationTransfer[],
) {
  const allocation = { ...baseBudgetAllocation }
  const movement = {
    necessidades: { in: 0, out: 0 },
    desejos: { in: 0, out: 0 },
    investimentos: { in: 0, out: 0 },
  }

  for (const transfer of transfers) {
    if (transfer.from === transfer.to || transfer.amount <= 0) continue
    const amount = Math.min(transfer.amount, allocation[transfer.from])
    if (amount <= 0) continue

    allocation[transfer.from] -= amount
    allocation[transfer.to] += amount
    movement[transfer.from].out += amount
    movement[transfer.to].in += amount
  }

  return { allocation, movement }
}

function isFixedIncomeSlice(name: string) {
  const normalized = name
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()

  return (
    normalized.includes('renda fixa') ||
    normalized.includes('tesouro') ||
    normalized.includes('selic') ||
    normalized.includes('cdb') ||
    normalized.includes('poupanca') ||
    normalized.includes('liquidez')
  )
}

function calculateCreditCardSummary(
  entries: CreditCardEntry[],
  settings: CreditCardSettings,
): CreditCardSummary {
  const currentEntries = entries.filter((entry) => entry.cycle === 'current')
  const nextEntries = entries.filter((entry) => entry.cycle === 'next')
  const currentTotal = currentEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const currentPersonalTotal = currentEntries.reduce((sum, entry) => sum + entry.personalAmount, 0)
  const currentThirdPartyTotal = currentEntries.reduce(
    (sum, entry) => sum + Math.max(0, entry.amount - entry.personalAmount),
    0,
  )
  const nextTotal = nextEntries.reduce((sum, entry) => sum + entry.amount, 0)
  const nextPersonalTotal = nextEntries.reduce((sum, entry) => sum + entry.personalAmount, 0)
  const remainingInstallmentsTotal = currentEntries.reduce((sum, entry) => sum + entry.remainingAmount, 0)
  const remainingPersonalInstallmentsTotal = currentEntries.reduce(
    (sum, entry) => sum + (entry.personalAmount / (entry.amount || 1)) * entry.remainingAmount,
    0,
  )
  const byCard = new Map<string, { totalAmount: number; personalAmount: number }>()
  const byOwner = new Map<string, { totalAmount: number; personalAmount: number }>()

  for (const entry of currentEntries) {
    const existing = byCard.get(entry.cardName) ?? { totalAmount: 0, personalAmount: 0 }
    byCard.set(entry.cardName, {
      totalAmount: existing.totalAmount + entry.amount,
      personalAmount: existing.personalAmount + entry.personalAmount,
    })

    const thirdPartyAmount = Math.max(0, entry.amount - entry.personalAmount)
    if (thirdPartyAmount > 0) {
      const owner = entry.ownerName || entry.ownerNote || 'Outro'
      const ownerExisting = byOwner.get(owner) ?? { totalAmount: 0, personalAmount: 0 }
      byOwner.set(owner, {
        totalAmount: ownerExisting.totalAmount + thirdPartyAmount,
        personalAmount: ownerExisting.personalAmount,
      })
    }
  }

  return {
    currentTotal,
    currentPersonalTotal,
    currentThirdPartyTotal,
    nextTotal,
    nextPersonalTotal,
    remainingInstallmentsTotal,
    remainingPersonalInstallmentsTotal,
    availablePersonalLimit: settings.personalSpendingLimit - currentPersonalTotal,
    totalsByCard: Array.from(byCard.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    totalsByOwner: Array.from(byOwner.entries())
      .map(([cardName, totals]) => ({ cardName, ...totals }))
      .sort((a, b) => b.totalAmount - a.totalAmount),
    currentEntriesCount: currentEntries.length,
    nextEntriesCount: nextEntries.length,
  }
}

function calculateScenario(state: FinanceScenarioData) {
  const safeState = normalizeScenario(state as FinanceScenario)
  const selectedModel = getSelectedModel(safeState)
  const totalCosts = safeState.costs.reduce((sum, c) => sum + c.value, 0)
  const totalDeductions = safeState.deductions.reduce((sum, d) => sum + d.value, 0)
  const investmentDeductions = safeState.deductions
    .filter((d) => INVESTMENT_DEDUCTION_TYPES.includes(d.type))
    .reduce((sum, d) => sum + d.value, 0)
  const employerInvestmentContributions = safeState.deductions
    .filter((d) => INVESTMENT_DEDUCTION_TYPES.includes(d.type))
    .reduce((sum, d) => sum + (d.employerContribution ?? 0), 0)
  const benefitDeductions = totalDeductions - investmentDeductions
  const paycheckInAccount =
    safeState.salaryInputMode === 'before_payroll_deductions'
      ? Math.max(0, safeState.salaryNet - totalDeductions)
      : safeState.salaryNet
  const availableForBudget =
    safeState.salaryInputMode === 'before_payroll_deductions'
      ? Math.max(0, safeState.salaryNet - benefitDeductions)
      : safeState.salaryNet + investmentDeductions

  const baseBudgetAllocation: Record<BudgetArea, number> = {
    necessidades: (availableForBudget * selectedModel.necessidades) / 100,
    desejos: (availableForBudget * selectedModel.desejos) / 100,
    investimentos: (availableForBudget * selectedModel.investimentos) / 100,
  }

  const { allocation: budgetAllocation, movement: allocationMovement } = applyAllocationTransfers(
    baseBudgetAllocation,
    safeState.allocationTransfers,
  )

  const necessidadesSurplus = Math.max(0, budgetAllocation.necessidades - totalCosts)
  const fixedWantsAmount = safeState.wants
    .filter((w) => (w.mode ?? 'percentage') === 'fixed')
    .reduce((sum, w) => sum + (w.fixedAmount ?? 0), 0)
  const variableWantsBase = Math.max(0, budgetAllocation.desejos - fixedWantsAmount)
  const totalWantsPercentage = safeState.wants
    .filter((w) => (w.mode ?? 'percentage') === 'percentage')
    .reduce((sum, w) => sum + w.percentage, 0)
  const wantAllocations = safeState.wants.map((w) => ({
    ...w,
    mode: w.mode ?? 'percentage',
    fixedAmount: w.fixedAmount ?? 0,
    amount:
      (w.mode ?? 'percentage') === 'fixed'
        ? w.fixedAmount ?? 0
        : (variableWantsBase * w.percentage) / 100,
  }))
  const totalWantsAmount = wantAllocations.reduce((sum, w) => sum + w.amount, 0)
  const totalDiversificationPercentage = safeState.diversification.reduce((sum, slice) => sum + slice.percentage, 0)
  const directInvestmentTarget = Math.max(
    0,
    budgetAllocation.investimentos - investmentDeductions,
  )
  const allocatedDirectInvestment = (directInvestmentTarget * totalDiversificationPercentage) / 100

  const budgetComparison: Record<string, BudgetBucket> = {
    necessidades: {
      target: budgetAllocation.necessidades,
      actual: totalCosts,
      diff: budgetAllocation.necessidades - totalCosts,
      percentage: budgetAllocation.necessidades > 0 ? (totalCosts / budgetAllocation.necessidades) * 100 : 0,
      baseTarget: baseBudgetAllocation.necessidades,
      movedIn: allocationMovement.necessidades.in,
      movedOut: allocationMovement.necessidades.out,
    },
    desejos: {
      target: budgetAllocation.desejos,
      actual: totalWantsAmount,
      diff: budgetAllocation.desejos - totalWantsAmount,
      percentage: budgetAllocation.desejos > 0 ? (totalWantsAmount / budgetAllocation.desejos) * 100 : 0,
      baseTarget: baseBudgetAllocation.desejos,
      movedIn: allocationMovement.desejos.in,
      movedOut: allocationMovement.desejos.out,
    },
    investimentos: {
      target: budgetAllocation.investimentos,
      actual: investmentDeductions + allocatedDirectInvestment,
      diff: budgetAllocation.investimentos - (investmentDeductions + allocatedDirectInvestment),
      percentage:
        budgetAllocation.investimentos > 0
          ? ((investmentDeductions + allocatedDirectInvestment) / budgetAllocation.investimentos) * 100
          : 0,
      baseTarget: baseBudgetAllocation.investimentos,
      movedIn: allocationMovement.investimentos.in,
      movedOut: allocationMovement.investimentos.out,
    },
  }

  const investmentAllocation = safeState.diversification.map((slice) => ({
    ...slice,
    amount: (directInvestmentTarget * slice.percentage) / 100,
  }))
  const fixedIncomeMonthlyAllocation = investmentAllocation
    .filter((slice) => isFixedIncomeSlice(slice.name))
    .reduce((sum, slice) => sum + slice.amount, 0)
  const creditCardSummary = calculateCreditCardSummary(safeState.creditCardEntries, safeState.creditCardSettings)

  const costsByCategory = new Map<string, number>()
  for (const c of safeState.costs) {
    costsByCategory.set(c.category, (costsByCategory.get(c.category) || 0) + c.value)
  }

  const balanceAfterCosts = paycheckInAccount - totalCosts - totalWantsAmount - allocatedDirectInvestment
  const unallocatedMoney = balanceAfterCosts

  return {
    selectedModel,
    totalCosts,
    totalDeductions,
    investmentDeductions,
    employerInvestmentContributions,
    benefitDeductions,
    paycheckInAccount,
    availableForBudget,
    baseBudgetAllocation,
    budgetAllocation,
    allocationMovement,
    necessidadesSurplus,
    fixedWantsAmount,
    variableWantsBase,
    totalWantsPercentage,
    wantAllocations,
    totalWantsAmount,
    totalDiversificationPercentage,
    directInvestmentTarget,
    allocatedDirectInvestment,
    budgetComparison,
    investmentAllocation,
    fixedIncomeMonthlyAllocation,
    creditCardSummary,
    costsByCategory,
    balanceAfterCosts,
    unallocatedMoney,
  }
}

export function useFinancas() {
  const [storedScenarios, setScenarios] = useLocalStorage<FinanceScenario[]>(
    SCENARIOS_STORAGE_KEY,
    loadInitialScenarios(),
  )
  const [activeScenarioId, setActiveScenarioId] = useLocalStorage<string>(
    ACTIVE_SCENARIO_STORAGE_KEY,
    storedScenarios[0]?.id ?? '',
  )
  const scenarios = useMemo(
    () => (Array.isArray(storedScenarios) ? storedScenarios.map(normalizeScenario) : []),
    [storedScenarios],
  )

  useEffect(() => {
    if (scenarios.length === 0) {
      const scenario = createDefaultScenario('Atual')
      setScenarios([scenario])
      setActiveScenarioId(scenario.id)
      return
    }

    if (!scenarios.some((scenario) => scenario.id === activeScenarioId)) {
      setActiveScenarioId(scenarios[0].id)
    }
  }, [activeScenarioId, scenarios, setActiveScenarioId, setScenarios])

  useEffect(() => {
    if (JSON.stringify(storedScenarios) !== JSON.stringify(scenarios)) {
      setScenarios(scenarios)
    }
  }, [scenarios, setScenarios, storedScenarios])

  const activeScenario = scenarios.find((scenario) => scenario.id === activeScenarioId) ?? scenarios[0] ?? createDefaultScenario('Atual')
  const activeId = activeScenario?.id ?? ''

  const updateActiveScenario = useCallback(
    (updater: (scenario: FinanceScenario) => FinanceScenario) => {
      setScenarios((prev) =>
        prev.map((scenario) =>
          scenario.id === activeId ? { ...updater(normalizeScenario(scenario)), updatedAt: nowIso() } : normalizeScenario(scenario),
        ),
      )
    },
    [activeId, setScenarios],
  )

  const setScenarioField = useCallback(
    <K extends keyof FinanceScenarioData>(field: K, value: FinanceScenarioData[K]) => {
      updateActiveScenario((scenario) => ({ ...scenario, [field]: value }))
    },
    [updateActiveScenario],
  )

  const createScenario = useCallback(
    (name = `Cenario ${scenarios.length + 1}`) => {
      const scenario = createDefaultScenario(name)
      setScenarios((prev) => [...prev, scenario])
      setActiveScenarioId(scenario.id)
    },
    [scenarios.length, setActiveScenarioId, setScenarios],
  )

  const duplicateScenario = useCallback(
    (sourceId = activeId) => {
      const source = scenarios.find((scenario) => scenario.id === sourceId) ?? activeScenario
      if (!source) return
      const scenario = cloneScenario(source, `${source.name} - futuro`)
      setScenarios((prev) => [...prev, scenario])
      setActiveScenarioId(scenario.id)
    },
    [activeId, activeScenario, scenarios, setActiveScenarioId, setScenarios],
  )

  const renameScenario = useCallback(
    (id: string, name: string) => {
      const trimmed = name.trim()
      if (!trimmed) return
      setScenarios((prev) =>
        prev.map((scenario) =>
          scenario.id === id ? { ...scenario, name: trimmed, updatedAt: nowIso() } : scenario,
        ),
      )
    },
    [setScenarios],
  )

  const removeScenario = useCallback(
    (id: string) => {
      if (scenarios.length <= 1) return
      const remaining = scenarios.filter((scenario) => scenario.id !== id)
      setScenarios(remaining)
      if (id === activeId) {
        setActiveScenarioId(remaining[0]?.id ?? '')
      }
    },
    [activeId, scenarios, setActiveScenarioId, setScenarios],
  )

  // Costs CRUD
  const addCost = useCallback(
    (name: string, value: number, category: CostCategory) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        costs: [...scenario.costs, { id: uid(), name, value, category }],
      }))
    },
    [updateActiveScenario],
  )

  const removeCost = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        costs: scenario.costs.filter((c) => c.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  // Wants CRUD
  const addWant = useCallback(
    (name: string, mode: 'percentage' | 'fixed' = 'percentage', fixedAmount = 0) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: [...scenario.wants, { id: uid(), name, mode, percentage: 0, fixedAmount }],
      }))
    },
    [updateActiveScenario],
  )

  const removeWant = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.filter((w) => w.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const updateWantPercentage = useCallback(
    (id: string, percentage: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.map((w) =>
          w.id === id ? { ...w, percentage: Math.max(0, Math.min(100, percentage)) } : w,
        ),
      }))
    },
    [updateActiveScenario],
  )

  const updateWantFixedAmount = useCallback(
    (id: string, fixedAmount: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.map((w) => (w.id === id ? { ...w, fixedAmount: Math.max(0, fixedAmount) } : w)),
      }))
    },
    [updateActiveScenario],
  )

  const updateWantMode = useCallback(
    (id: string, mode: 'percentage' | 'fixed') => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        wants: scenario.wants.map((w) =>
          w.id === id
            ? {
                ...w,
                mode,
                percentage: mode === 'percentage' ? w.percentage : 0,
                fixedAmount: mode === 'fixed' ? w.fixedAmount ?? 0 : 0,
              }
            : w,
        ),
      }))
    },
    [updateActiveScenario],
  )

  // Deductions CRUD
  const addDeduction = useCallback(
    (name: string, value: number, type: DeductionType, employerContribution = 0) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: [...scenario.deductions, { id: uid(), name, value, type, employerContribution }],
      }))
    },
    [updateActiveScenario],
  )

  const removeDeduction = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: scenario.deductions.filter((d) => d.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const updateDeductionEmployerContribution = useCallback(
    (id: string, employerContribution: number) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        deductions: scenario.deductions.map((d) =>
          d.id === id ? { ...d, employerContribution: Math.max(0, employerContribution) } : d,
        ),
      }))
    },
    [updateActiveScenario],
  )

  // Diversification
  const updateDiversification = useCallback(
    (slices: DiversificationSlice[]) => {
      setScenarioField('diversification', slices)
    },
    [setScenarioField],
  )

  const addDiversificationSlice = useCallback(
    (name: string, percentage: number, color: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        diversification: [...scenario.diversification, { id: uid(), name, percentage, color }],
      }))
    },
    [updateActiveScenario],
  )

  const removeDiversificationSlice = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        diversification: scenario.diversification.filter((s) => s.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const addAllocationTransfer = useCallback(
    (from: BudgetArea, to: BudgetArea, amount: number) => {
      if (from === to || amount <= 0) return
      updateActiveScenario((scenario) => ({
        ...scenario,
        allocationTransfers: [...scenario.allocationTransfers, { id: uid(), from, to, amount }],
      }))
    },
    [updateActiveScenario],
  )

  const removeAllocationTransfer = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => ({
        ...scenario,
        allocationTransfers: scenario.allocationTransfers.filter((transfer) => transfer.id !== id),
      }))
    },
    [updateActiveScenario],
  )

  const clearAllocationTransfers = useCallback(() => {
    updateActiveScenario((scenario) => ({ ...scenario, allocationTransfers: [] }))
  }, [updateActiveScenario])

  const addCreditCardEntry = useCallback(
    (entry: Omit<CreditCardEntry, 'id'>) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [...scenario.creditCardEntries, normalizeCreditCardEntry({ ...entry, id: uid() })]
        return {
          ...scenario,
          creditCardEntries: entry.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const updateCreditCardEntry = useCallback(
    (id: string, patch: Partial<Omit<CreditCardEntry, 'id'>>) => {
      updateActiveScenario((scenario) => {
        const target = scenario.creditCardEntries.find((entry) => entry.id === id)
        if (!target) return scenario

        // Editar um lançamento gerado automaticamente o torna manual,
        // para a edição não ser descartada na próxima sincronização.
        const effectivePatch =
          target.cycle === 'next' && target.autoGenerated ? { ...patch, autoGenerated: false } : patch
        const nextEntries = scenario.creditCardEntries.map((entry) =>
          entry.id === id ? normalizeCreditCardEntry({ ...entry, ...effectivePatch }) : entry,
        )

        return {
          ...scenario,
          creditCardEntries: target.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const removeCreditCardEntry = useCallback(
    (id: string) => {
      updateActiveScenario((scenario) => {
        const target = scenario.creditCardEntries.find((entry) => entry.id === id)
        const nextEntries = scenario.creditCardEntries.filter((entry) => entry.id !== id)
        return {
          ...scenario,
          creditCardEntries: target?.cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const replaceCreditCardEntries = useCallback(
    (cycle: CreditCardCycle, entries: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [
          ...scenario.creditCardEntries.filter((entry) => entry.cycle !== cycle),
          ...entries.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return {
          ...scenario,
          creditCardEntries: cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const appendCreditCardEntries = useCallback(
    (cycle: CreditCardCycle, entries: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      updateActiveScenario((scenario) => {
        const nextEntries = [
          ...scenario.creditCardEntries,
          ...entries.map((entry) => normalizeCreditCardEntry({ ...entry, cycle, id: uid() })),
        ]
        return {
          ...scenario,
          creditCardEntries: cycle === 'current' ? syncGeneratedNextEntries(nextEntries) : nextEntries,
        }
      })
    },
    [updateActiveScenario],
  )

  const anticipateCreditCardInstallments = useCallback(
    (id: string, count: number) => {
      updateActiveScenario((scenario) => {
        const entry = scenario.creditCardEntries.find((item) => item.id === id)
        if (!entry || entry.cycle !== 'current' || !entry.installmentCurrent || !entry.installmentTotal) {
          return scenario
        }

        const current = entry.installmentCurrent
        const total = entry.installmentTotal
        const quantity = Math.min(Math.max(1, Math.floor(count)), total - current)
        if (quantity < 1) return scenario

        // Cada parcela antecipada vira um lançamento próprio na fatura atual;
        // o valor restante da compra fica concentrado na última parcela lançada.
        const anticipated = Array.from({ length: quantity }, (_, index) => {
          const installment = current + index + 1
          return normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            installmentCurrent: installment,
            remainingAmount:
              installment === current + quantity
                ? buildRemainingInstallmentsAmount(entry.amount, installment, total)
                : 0,
          })
        })

        const nextEntries = [
          ...scenario.creditCardEntries.map((item) => (item.id === id ? { ...item, remainingAmount: 0 } : item)),
          ...anticipated,
        ]

        return { ...scenario, creditCardEntries: syncGeneratedNextEntries(nextEntries) }
      })
    },
    [updateActiveScenario],
  )

  const payCreditCardInvoice = useCallback(() => {
    updateActiveScenario((scenario) => {
      // Sincroniza antes de virar o ciclo: dados criados antes da geração
      // automática podem ainda não ter as parcelas materializadas na próxima.
      const syncedEntries = syncGeneratedNextEntries(scenario.creditCardEntries)
      const newCurrentEntries = syncedEntries
        .filter((entry) => entry.cycle === 'next')
        .map((entry) =>
          normalizeCreditCardEntry({
            ...entry,
            id: uid(),
            cycle: 'current',
            autoGenerated: false,
            sourceEntryId: undefined,
          }),
        )

      return { ...scenario, creditCardEntries: syncGeneratedNextEntries(newCurrentEntries) }
    })
  }, [updateActiveScenario])

  const setCreditCardSettings = useCallback(
    (settings: CreditCardSettings) => {
      setScenarioField('creditCardSettings', {
        ...settings,
        personalSpendingLimit: Math.max(0, settings.personalSpendingLimit),
      })
    },
    [setScenarioField],
  )

  const metrics = useMemo(() => calculateScenario(activeScenario), [activeScenario])

  const scenarioSummaries = useMemo<ScenarioSummary[]>(
    () =>
      scenarios.map((scenario) => {
        const summary = calculateScenario(scenario)
        const savingsRate =
          summary.availableForBudget > 0
            ? (summary.budgetComparison.investimentos.actual / summary.availableForBudget) * 100
            : 0

        return {
          id: scenario.id,
          name: scenario.name,
          salaryNet: scenario.salaryNet,
          paycheckInAccount: summary.paycheckInAccount,
          availableForBudget: summary.availableForBudget,
          totalCosts: summary.totalCosts,
          totalWantsAmount: summary.totalWantsAmount,
          investmentDeductions: summary.investmentDeductions,
          employerInvestmentContributions: summary.employerInvestmentContributions,
          directInvestmentTarget: summary.directInvestmentTarget,
          balanceAfterCosts: summary.balanceAfterCosts,
          savingsRate,
        }
      }),
    [scenarios],
  )

  return {
    scenarios,
    activeScenario,
    activeScenarioId: activeId,
    setActiveScenarioId,
    createScenario,
    duplicateScenario,
    renameScenario,
    removeScenario,
    scenarioSummaries,
    salaryNet: activeScenario.salaryNet,
    setSalaryNet: (value: number) => setScenarioField('salaryNet', value),
    salaryInputMode: activeScenario.salaryInputMode,
    setSalaryInputMode: (mode: SalaryInputMode) => setScenarioField('salaryInputMode', mode),
    paycheckInAccount: metrics.paycheckInAccount,
    costs: activeScenario.costs,
    addCost,
    removeCost,
    wants: activeScenario.wants,
    addWant,
    removeWant,
    updateWantPercentage,
    updateWantFixedAmount,
    updateWantMode,
    wantAllocations: metrics.wantAllocations,
    totalWantsPercentage: metrics.totalWantsPercentage,
    fixedWantsAmount: metrics.fixedWantsAmount,
    variableWantsBase: metrics.variableWantsBase,
    totalWantsAmount: metrics.totalWantsAmount,
    deductions: activeScenario.deductions,
    addDeduction,
    removeDeduction,
    updateDeductionEmployerContribution,
    selectedModelId: activeScenario.selectedModelId,
    setSelectedModelId: (id: string) => setScenarioField('selectedModelId', id),
    selectedModel: metrics.selectedModel,
    customModel: activeScenario.customModel,
    setCustomModel: (model: { n: number; d: number; i: number }) => setScenarioField('customModel', model),
    diversification: activeScenario.diversification,
    updateDiversification,
    addDiversificationSlice,
    removeDiversificationSlice,
    totalCosts: metrics.totalCosts,
    totalDeductions: metrics.totalDeductions,
    investmentDeductions: metrics.investmentDeductions,
    employerInvestmentContributions: metrics.employerInvestmentContributions,
    benefitDeductions: metrics.benefitDeductions,
    availableForBudget: metrics.availableForBudget,
    baseBudgetAllocation: metrics.baseBudgetAllocation,
    budgetAllocation: metrics.budgetAllocation,
    allocationTransfers: activeScenario.allocationTransfers,
    addAllocationTransfer,
    removeAllocationTransfer,
    clearAllocationTransfers,
    necessidadesSurplus: metrics.necessidadesSurplus,
    surplusToDesejos: activeScenario.surplusToDesejos,
    setSurplusToDesejos: (value: number) => setScenarioField('surplusToDesejos', value),
    budgetComparison: metrics.budgetComparison,
    directInvestmentTarget: metrics.directInvestmentTarget,
    totalDiversificationPercentage: metrics.totalDiversificationPercentage,
    investmentAllocation: metrics.investmentAllocation,
    fixedIncomeMonthlyAllocation: metrics.fixedIncomeMonthlyAllocation,
    costsByCategory: metrics.costsByCategory,
    balanceAfterCosts: metrics.balanceAfterCosts,
    unallocatedMoney: metrics.unallocatedMoney,
    emergencyFundCurrent: activeScenario.emergencyFundCurrent,
    setEmergencyFundCurrent: (value: number) => setScenarioField('emergencyFundCurrent', value),
    creditCardEntries: activeScenario.creditCardEntries,
    creditCardSettings: activeScenario.creditCardSettings,
    creditCardSummary: metrics.creditCardSummary,
    addCreditCardEntry,
    updateCreditCardEntry,
    removeCreditCardEntry,
    replaceCreditCardEntries,
    appendCreditCardEntries,
    anticipateCreditCardInstallments,
    payCreditCardInvoice,
    setCreditCardSettings,
  }
}
