import type { BudgetArea } from './core'

export type CreditCardCycle = 'current' | 'next'

export interface CreditCardEntry {
  id: string
  cycle: CreditCardCycle
  description: string
  purchaseDate: string
  cardName: string
  amount: number
  personalAmount: number
  remainingAmount: number
  budgetArea?: BudgetArea
  ownerName?: string
  ownerNote?: string
  installmentCurrent?: number
  installmentTotal?: number
  isRecurring?: boolean
  isPrepaid?: boolean
  autoGenerated?: boolean
  sourceEntryId?: string
}

export interface CreditCardSettings {
  paymentDate: string
  personalSpendingLimit: number
  currentDueMonth?: string
}

export interface CreditCardAccount {
  id: string
  name: string
  closingDay: number
  dueDay: number
  limit: number
}

export interface CardCycleStatus extends CreditCardAccount {
  isClosed: boolean
  daysToClosing: number
  daysToDue: number
  personalAmount: number
  totalAmount: number
  usagePct: number | null
}

export interface CardTotal {
  cardName: string
  totalAmount: number
  personalAmount: number
  thirdPartyAmount: number
}

export interface CreditCardSummary {
  currentTotal: number
  currentPersonalTotal: number
  currentThirdPartyTotal: number
  currentPrepaidTotal: number
  currentPersonalPrepaidTotal: number
  nextTotal: number
  nextPersonalTotal: number
  remainingInstallmentsTotal: number
  remainingPersonalInstallmentsTotal: number
  availablePersonalLimit: number
  totalsByCard: CardTotal[]
  totalsByOwner: CardTotal[]
  currentEntriesCount: number
  nextEntriesCount: number
  personalByArea: Record<BudgetArea, number>
  unclassifiedPersonal: number
}
