// ---------------------------------------------------------------------------
// Vocabulário base
// ---------------------------------------------------------------------------

export type BudgetArea = 'necessidades' | 'desejos' | 'investimentos'

export type SalaryInputMode = 'before_payroll_deductions' | 'take_home'

/**
 * Movimentação de um livro-razão (reserva, posição de investimento, meta).
 * Positivo = entrada/aporte, negativo = saída/retirada.
 */
export interface LedgerEntry {
  id: string
  amount: number
  date: string
  note?: string
}

// ---------------------------------------------------------------------------
// Orçamento do mês
// ---------------------------------------------------------------------------

export type CostCategory =
  | 'moradia'
  | 'contas'
  | 'alimentacao'
  | 'transporte'
  | 'saude'
  | 'educacao'
  | 'lazer'
  | 'dividas'
  | 'outros'

export interface CostItem {
  id: string
  name: string
  /** Valor cheio da conta, incluindo a parte de terceiros. */
  value: number
  category: CostCategory
  /** Parte bancada por outra pessoa — sai do seu orçamento. */
  sharedAmount?: number
  /** Com quem o custo é dividido. */
  sharedWith?: string
}

export interface WantItem {
  id: string
  name: string
  plannedAmount: number
}

export type DeductionType =
  | 'previdencia_privada'
  | 'plano_saude'
  | 'vale_alimentacao'
  | 'vale_transporte'
  | 'seguro_vida'
  | 'outros'

export interface DeductionItem {
  id: string
  name: string
  value: number
  type: DeductionType
  employerContribution?: number
}

export interface BudgetModel {
  id: string
  name: string
  description: string
  necessidades: number
  desejos: number
  investimentos: number
}

export interface DiversificationSlice {
  id: string
  name: string
  percentage: number
  color: string
}

export interface BudgetBucket {
  target: number
  /** O que o plano prevê gastar/investir. */
  actual: number
  /** O que já foi de fato gasto no cartão nesta área. */
  realized: number
  diff: number
  percentage: number
}

// ---------------------------------------------------------------------------
// Patrimônio — reserva, posições e metas (módulos globais, fora do cenário)
// ---------------------------------------------------------------------------

export interface EmergencyFundState {
  /** Saldo guardado — derivado da soma das transações. */
  current: number
  targetMonths: number
  transactions: LedgerEntry[]
}

/** Objetivo com nome, valor-alvo e prazo — ex.: "Viagem Japão". */
export interface FinancialGoal {
  id: string
  name: string
  targetAmount: number
  /** Mês-alvo no formato AAAA-MM. */
  targetMonth?: string
  color: string
  transactions: LedgerEntry[]
  createdAt: string
  completedAt?: string
}

export interface GoalSummary extends FinancialGoal {
  current: number
  remaining: number
  progress: number
  /** Meses restantes até o mês-alvo (negativo = atrasada). */
  monthsLeft: number | null
  /** Quanto aportar por mês para chegar no prazo. */
  suggestedMonthly: number
  isComplete: boolean
}

export interface InvestmentAssetClass {
  id: string
  name: string
  color: string
}

export interface InvestmentHolding {
  id: string
  name: string
  assetClassId: string
  institution?: string
  /** Saldo atual de mercado, atualizado pelo usuário (marcação a mercado). */
  marketValue: number
  transactions: LedgerEntry[]
}

export interface HoldingSummary extends InvestmentHolding {
  invested: number
  gain: number
  gainPct: number
  /** Retorno anualizado estimado a partir das datas dos aportes. */
  annualizedPct: number | null
}

export interface AssetClassSummary {
  id: string
  name: string
  color: string
  marketValue: number
  invested: number
  gain: number
  gainPct: number
  /** Fatia do patrimônio total (inclui reserva e metas). */
  allocationPct: number
  holdings: HoldingSummary[]
}

export interface InvestmentsSummary {
  totalMarketValue: number
  totalInvested: number
  totalGain: number
  totalGainPct: number
  /** Investimentos + reserva + metas. */
  netWorth: number
  reserveBalance: number
  goalsBalance: number
  classes: AssetClassSummary[]
}

// ---------------------------------------------------------------------------
// Cartões de crédito
// ---------------------------------------------------------------------------

export type CreditCardCycle = 'current' | 'next'

export interface CreditCardEntry {
  id: string
  cycle: CreditCardCycle
  description: string
  purchaseDate: string
  cardName: string
  amount: number
  personalAmount: number
  remainingAmount: number
  /** Área do orçamento que a compra consome — liga a fatura ao plano. */
  budgetArea?: BudgetArea
  ownerName?: string
  ownerNote?: string
  installmentCurrent?: number
  installmentTotal?: number
  isRecurring?: boolean
  /** Compra já paga antecipadamente: continua listada, mas fora dos totais da fatura. */
  isPrepaid?: boolean
  autoGenerated?: boolean
  sourceEntryId?: string
}

export interface CreditCardSettings {
  paymentDate: string
  personalSpendingLimit: number
}

export interface CardTotal {
  cardName: string
  totalAmount: number
  personalAmount: number
}

export interface CreditCardSummary {
  currentTotal: number
  currentPersonalTotal: number
  currentThirdPartyTotal: number
  currentPrepaidTotal: number
  currentPersonalPrepaidTotal: number
  nextTotal: number
  nextPersonalTotal: number
  remainingInstallmentsTotal: number
  remainingPersonalInstallmentsTotal: number
  availablePersonalLimit: number
  totalsByCard: CardTotal[]
  totalsByOwner: CardTotal[]
  currentEntriesCount: number
  nextEntriesCount: number
  /** Gasto pessoal do ciclo atual por área do orçamento. */
  personalByArea: Record<BudgetArea, number>
  /** Gasto pessoal ainda sem área definida. */
  unclassifiedPersonal: number
}

// ---------------------------------------------------------------------------
// Cenários
// ---------------------------------------------------------------------------

export interface FinanceScenarioData {
  salaryNet: number
  salaryInputMode: SalaryInputMode
  costs: CostItem[]
  wants: WantItem[]
  deductions: DeductionItem[]
  selectedModelId: string
  diversification: DiversificationSlice[]
  customModel: { n: number; d: number; i: number }
}

export interface FinanceScenario extends FinanceScenarioData {
  id: string
  name: string
  createdAt: string
  updatedAt: string
}

export interface ScenarioSummary {
  id: string
  name: string
  availableForBudget: number
  totalCosts: number
  totalWantsAmount: number
  totalPlannedInvestment: number
  balanceAfterPlan: number
  savingsRate: number
}

// ---------------------------------------------------------------------------
// Histórico — o que de fato aconteceu em cada mês
// ---------------------------------------------------------------------------

export interface MonthlySnapshot {
  id: string
  /** Mês de competência no formato AAAA-MM. */
  month: string
  closedAt: string
  scenarioId: string
  scenarioName: string
  availableForBudget: number
  paycheckInAccount: number
  costs: number
  wants: number
  invested: number
  balance: number
  savingsRate: number
  costsByCategory: Partial<Record<CostCategory, number>>
  /** Patrimônio no fechamento (investimentos + reserva + metas). */
  netWorth: number
  emergencyFund: number
  cardPersonalTotal: number
  note?: string
}

export interface HistoryPoint extends MonthlySnapshot {
  /** Variação do patrimônio em relação ao mês fechado anterior. */
  netWorthDelta: number | null
  costsDelta: number | null
}

export interface HistoryStats {
  months: number
  averageCosts: number
  averageWants: number
  averageInvested: number
  averageSavingsRate: number
  netWorthGrowth: number
  netWorthGrowthPct: number
  bestSavingsMonth: MonthlySnapshot | null
}
