export interface CostItem {
  id: string
  name: string
  value: number
  category: CostCategory
}

export type CostCategory =
  | 'moradia'
  | 'contas'
  | 'alimentacao'
  | 'transporte'
  | 'saude'
  | 'educacao'
  | 'lazer'
  | 'dividas'
  | 'outros'

export interface WantItem {
  id: string
  name: string
  plannedAmount: number
}

export interface DeductionItem {
  id: string
  name: string
  value: number
  type: DeductionType
  employerContribution?: number
}

export type DeductionType =
  | 'previdencia_privada'
  | 'plano_saude'
  | 'vale_alimentacao'
  | 'vale_transporte'
  | 'seguro_vida'
  | 'outros'

export interface BudgetModel {
  id: string
  name: string
  description: string
  necessidades: number
  desejos: number
  investimentos: number
}

export interface DiversificationSlice {
  id: string
  name: string
  percentage: number
  color: string
}

export interface EmergencyFundTransaction {
  id: string
  /** Positivo = aporte, negativo = retirada. */
  amount: number
  date: string
  note?: string
}

export interface EmergencyFundState {
  /** Saldo guardado — derivado da soma das transações. */
  current: number
  targetMonths: number
  transactions: EmergencyFundTransaction[]
}

// ---------------------------------------------------------------------------
// Investimentos (patrimônio) — módulo global, independente de cenário.
// Uma classe de ativo (ex.: Renda Fixa) agrupa posições (ex.: CDB Itaú).
// Cada posição tem um livro-razão de aportes/retiradas e um valor de mercado
// atual; o rendimento é valor de mercado menos o total aportado.
// ---------------------------------------------------------------------------

export interface InvestmentTransaction {
  id: string
  /** Positivo = aporte, negativo = retirada. */
  amount: number
  date: string
  note?: string
}

export interface InvestmentAssetClass {
  id: string
  name: string
  color: string
}

export interface InvestmentHolding {
  id: string
  name: string
  assetClassId: string
  institution?: string
  /** Saldo atual de mercado, atualizado pelo usuário (marcação a mercado). */
  marketValue: number
  transactions: InvestmentTransaction[]
}

export interface HoldingSummary extends InvestmentHolding {
  invested: number
  gain: number
  gainPct: number
}

export interface AssetClassSummary {
  id: string
  name: string
  color: string
  marketValue: number
  invested: number
  gain: number
  gainPct: number
  allocationPct: number
  holdings: HoldingSummary[]
}

export interface InvestmentsSummary {
  totalMarketValue: number
  totalInvested: number
  totalGain: number
  totalGainPct: number
  classes: AssetClassSummary[]
}

export type CreditCardCycle = 'current' | 'next'

export interface CreditCardEntry {
  id: string
  cycle: CreditCardCycle
  description: string
  purchaseDate: string
  cardName: string
  amount: number
  personalAmount: number
  remainingAmount: number
  ownerName?: string
  ownerNote?: string
  installmentCurrent?: number
  installmentTotal?: number
  isRecurring?: boolean
  /** Compra já paga antecipadamente: continua listada, mas fora dos totais da fatura. */
  isPrepaid?: boolean
  autoGenerated?: boolean
  sourceEntryId?: string
}

export interface CreditCardSettings {
  paymentDate: string
  personalSpendingLimit: number
}

export interface CardTotal {
  cardName: string
  totalAmount: number
  personalAmount: number
}

export interface CreditCardSummary {
  currentTotal: number
  currentPersonalTotal: number
  currentThirdPartyTotal: number
  currentPrepaidTotal: number
  currentPersonalPrepaidTotal: number
  nextTotal: number
  nextPersonalTotal: number
  remainingInstallmentsTotal: number
  remainingPersonalInstallmentsTotal: number
  availablePersonalLimit: number
  totalsByCard: CardTotal[]
  totalsByOwner: CardTotal[]
  currentEntriesCount: number
  nextEntriesCount: number
}

export interface BudgetBucket {
  target: number
  actual: number
  diff: number
  percentage: number
}

export type SalaryInputMode = 'before_payroll_deductions' | 'take_home'

export type BudgetArea = 'necessidades' | 'desejos' | 'investimentos'

export interface FinanceScenarioData {
  salaryNet: number
  salaryInputMode: SalaryInputMode
  costs: CostItem[]
  wants: WantItem[]
  deductions: DeductionItem[]
  selectedModelId: string
  diversification: DiversificationSlice[]
  customModel: { n: number; d: number; i: number }
}

export interface FinanceScenario extends FinanceScenarioData {
  id: string
  name: string
  createdAt: string
  updatedAt: string
}

export interface ScenarioSummary {
  id: string
  name: string
  availableForBudget: number
  totalCosts: number
  totalWantsAmount: number
  totalPlannedInvestment: number
  balanceAfterPlan: number
  savingsRate: number
}
